export const MESSAGE_TYPES = [
  "HELLO", "OPEN_SESSION", "OPEN_SESSION_RESULT", "ACTION_REQUEST", "ACTION_RECEIPT",
  "ACTION_COMPLETION", "EVENT_DRAFT", "SOURCE_LEASE_OPEN", "SOURCE_LEASE_CLOSE",
  "SOURCE_ATTEMPT", "FAULT_STATUS", "FENCE_STATUS", "CAPTURE_REQUEST", "CAPTURE_RESULT",
  "CLOSE_SESSION", "CLOSE_SESSION_RESULT", "ADAPTER_ERROR",
] as const;

export type MessageType = (typeof MESSAGE_TYPES)[number];
export const MESSAGE_TYPE_SET: ReadonlySet<string> = new Set(MESSAGE_TYPES);

export const COMPLETION_OUTCOMES = ["SUCCEEDED", "FAILED", "CANCELLED"] as const;
export type CompletionOutcome = (typeof COMPLETION_OUTCOMES)[number];
