#include "canvas/semantic/delete_closure.hpp"
#include "canvas/semantic/indexed_object_store.hpp"
#include "canvas/semantic/reference_object_store.hpp"
#include "canvas/semantic/staged_object_view.hpp"
#include "delete_closure_internal.hpp"
#include "object_store_mutator.hpp"
#include <gtest/gtest.h>
#include <algorithm>
#include <map>
#include <optional>
#include <set>
#include <span>
#include <vector>
namespace canvas::semantic { namespace {
ObjectId id(std::uint64_t value){ return ObjectId::fromUint64(value); }
ObjectRecord shape(std::uint64_t value,std::optional<ObjectId> parent=std::nullopt){ ObjectRecord r{}; r.id=id(value); r.kind=ObjectKind::kShape; r.kind_version=1U; r.placement.parent_id=parent; r.placement.order_key=OrderKey({static_cast<std::uint8_t>(value)}); r.content=ShapeContent{1U,10.0,10.0}; return r; }
ObjectRecord connector(std::uint64_t value,std::optional<ObjectId> start,std::optional<ObjectId> end=std::nullopt){ ObjectRecord r{}; r.id=id(value); r.kind=ObjectKind::kConnector; r.kind_version=1U; r.placement.order_key=OrderKey({static_cast<std::uint8_t>(value)}); ConnectorContent c{}; if(start)c.start.value=AttachedEndpoint{*start,AutoPerimeterAnchor{}}; if(end)c.end.value=AttachedEndpoint{*end,AutoPerimeterAnchor{}}; r.content=c; return r; }
template<typename S> void insert(S& s,const ObjectRecord& r){ ASSERT_TRUE(internal::ObjectStoreMutator::insertFresh(s,r)); }
DeleteClosure resolve(const StagedObjectView& s,std::initializer_list<ObjectId> q){ DeleteClosure c{}; const auto result=resolveDeleteClosure(s,std::span<const ObjectId>(q.begin(),q.size()),&c); EXPECT_TRUE(result.ok()); return c; }
DeleteClosure oracle(const std::map<ObjectId,std::vector<ObjectId>>& h,const std::map<ObjectId,std::vector<ObjectId>>& rev,std::vector<ObjectId> req){ std::set<ObjectId> all(req.begin(),req.end()), hs, cs; std::vector<ObjectId> f=req; while(!f.empty()){ std::vector<ObjectId> n; for(auto p:f){auto hi=h.find(p);if(hi==h.end())continue;for(auto x:hi->second) if(all.insert(x).second){hs.insert(x);n.push_back(x);}} auto rel=f; rel.insert(rel.end(),n.begin(),n.end()); for(auto t:rel){auto it=rev.find(t); if(it==rev.end())continue; for(auto x:it->second) if(all.insert(x).second){cs.insert(x);n.push_back(x);}} std::sort(n.begin(),n.end()); n.erase(std::unique(n.begin(),n.end()),n.end()); f=std::move(n);} DeleteClosure c; c.requested_delete_ids=std::move(req); c.resolved_hierarchy_closure.assign(hs.begin(),hs.end()); c.resolved_connector_cascade_closure.assign(cs.begin(),cs.end()); c.final_delete_set.assign(all.begin(),all.end()); return c; }
void expectClosureEqual(const DeleteClosure& actual,const DeleteClosure& expected){ EXPECT_EQ(actual.requested_delete_ids,expected.requested_delete_ids); EXPECT_EQ(actual.resolved_hierarchy_closure,expected.resolved_hierarchy_closure); EXPECT_EQ(actual.resolved_connector_cascade_closure,expected.resolved_connector_cascade_closure); EXPECT_EQ(actual.final_delete_set,expected.final_delete_set); }
TEST(DeleteClosure, IndependentOracleDirectDescendantMultiple){ ReferenceObjectStore b; insert(b,shape(1));insert(b,shape(2,id(1)));insert(b,connector(10,id(1)));insert(b,connector(11,id(2))); StagedObjectView s(b); auto a=resolve(s,{id(1)}); auto e=oracle({{id(1),{id(2)}},{id(2),{}}},{{id(1),{id(10)}},{id(2),{id(11)}}},{id(1)}); EXPECT_EQ(a.final_delete_set,e.final_delete_set); EXPECT_EQ(a.resolved_hierarchy_closure,e.resolved_hierarchy_closure); EXPECT_EQ(a.resolved_connector_cascade_closure,e.resolved_connector_cascade_closure); }
TEST(DeleteClosure, EndpointDedupFreeFree){ ReferenceObjectStore b;insert(b,shape(1));insert(b,shape(2));insert(b,connector(10,id(1),id(1)));insert(b,connector(11,std::nullopt,std::nullopt));StagedObjectView s(b);EXPECT_EQ(resolve(s,{id(1),id(2)}).resolved_connector_cascade_closure,std::vector<ObjectId>({id(10)})); }
TEST(DeleteClosure, TwoDistinctConnectorsReferencingOneTarget){ ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));insert(b,connector(11,id(1)));StagedObjectView s(b);auto c=resolve(s,{id(1)});EXPECT_EQ(c.resolved_connector_cascade_closure,std::vector<ObjectId>({id(10),id(11)}));EXPECT_EQ(c.final_delete_set,std::vector<ObjectId>({id(1),id(10),id(11)})); }
TEST(DeleteClosure, RequestedAndHierarchyReasons){ ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));insert(b,shape(2,id(10)));StagedObjectView s(b);EXPECT_TRUE(resolve(s,{id(1),id(10)}).resolved_connector_cascade_closure.empty());auto c=resolve(s,{id(10)});EXPECT_EQ(c.resolved_hierarchy_closure,std::vector<ObjectId>({id(2)}));EXPECT_TRUE(c.resolved_connector_cascade_closure.empty()); }
TEST(DeleteClosure, HierarchyIncludedConnectorExcludedFromCascadePartition){ ReferenceObjectStore b;insert(b,shape(1));insert(b,shape(9));insert(b,connector(10,id(1)));auto child=connector(20,id(1));child.placement.parent_id=id(9);insert(b,child);StagedObjectView s(b);auto c=resolve(s,{id(9)});EXPECT_EQ(c.resolved_hierarchy_closure,std::vector<ObjectId>({id(20)}));EXPECT_TRUE(c.resolved_connector_cascade_closure.empty()); }
TEST(DeleteClosure, MultiWave){ ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));insert(b,shape(2,id(10)));insert(b,connector(20,id(2)));StagedObjectView s(b);auto out=resolve(s,{id(1)});EXPECT_EQ(out.resolved_hierarchy_closure,std::vector<ObjectId>({id(2)}));EXPECT_EQ(out.resolved_connector_cascade_closure,std::vector<ObjectId>({id(10),id(20)}));EXPECT_EQ(out.final_delete_set,std::vector<ObjectId>({id(1),id(2),id(10),id(20)})); }
TEST(DeleteClosure, RuntimeTraceCapturesFixedPointMetrics){ class C final:public ObjectStore{public:explicit C(const ObjectStore&d):d_(d){}std::size_t size()const noexcept override{return d_.size();}bool contains(const ObjectId&x)const noexcept override{return d_.contains(x);}const ObjectRecord* find(const ObjectId&x)const noexcept override{++finds;return d_.find(x);}std::vector<ObjectRecord> allObjects()const override{++alls;return d_.allObjects();}std::vector<ObjectRecord> children(const std::optional<ObjectId>&p)const override{++childs;return d_.children(p);}mutable std::size_t alls=0,childs=0,finds=0;private:const ObjectStore&d_;};ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));insert(b,shape(2,id(10)));insert(b,connector(20,id(2)));C c(b);StagedObjectView s(c);DeleteClosure out;internal::DeleteClosureTrace trace;const ObjectId requested[]={id(1)};const auto result=internal::resolveDeleteClosureWithTrace(s,std::span<const ObjectId>(requested,1),&out,&trace);ASSERT_TRUE(result.ok());EXPECT_EQ(out.final_delete_set,std::vector<ObjectId>({id(1),id(2),id(10),id(20)}));EXPECT_EQ(c.alls,1U);EXPECT_EQ(c.childs,4U);EXPECT_EQ(c.finds,1U);EXPECT_EQ(trace.fixed_point_waves,3U);EXPECT_EQ(trace.reverse_relation_lookups,5U);ASSERT_EQ(trace.waves.size(),3U);EXPECT_TRUE(trace.waves[0].hierarchy_additions.empty());EXPECT_EQ(trace.waves[0].connector_additions,std::vector<ObjectId>({id(10)}));EXPECT_EQ(trace.waves[1].hierarchy_additions,std::vector<ObjectId>({id(2)}));EXPECT_EQ(trace.waves[1].connector_additions,std::vector<ObjectId>({id(20)}));EXPECT_TRUE(trace.waves[2].hierarchy_additions.empty());EXPECT_TRUE(trace.waves[2].connector_additions.empty()); }
TEST(DeleteClosure, DeterministicRepeatedParity){ ReferenceObjectStore a,b;IndexedObjectStore i; auto x=shape(1),y=shape(2,id(1)),c1=connector(10,id(1)),c2=connector(20,id(2));insert(a,x);insert(a,y);insert(a,c1);insert(a,c2);insert(b,c2);insert(b,y);insert(b,c1);insert(b,x);insert(i,x);insert(i,y);insert(i,c1);insert(i,c2);StagedObjectView sa(a),sb(b),si(i);auto ra=resolve(sa,{id(1)}),rb=resolve(sb,{id(1)}),ri=resolve(si,{id(1)});expectClosureEqual(ra,rb);expectClosureEqual(ra,ri);expectClosureEqual(ra,resolve(sa,{id(1)})); }
TEST(DeleteClosure, StagedCreateReplaceDelete){ ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));StagedObjectView s(b);ASSERT_TRUE(s.stageDelete(id(10)));ASSERT_TRUE(s.stageCreate(connector(20,id(1))));EXPECT_EQ(resolve(s,{id(1)}).resolved_connector_cascade_closure,std::vector<ObjectId>({id(20)}));ASSERT_TRUE(s.stageReplace(connector(20,std::nullopt,std::nullopt)));EXPECT_TRUE(resolve(s,{id(1)}).resolved_connector_cascade_closure.empty()); }
TEST(DeleteClosure, NoMutationAndSingleProjectionScan){ class C final:public ObjectStore{public:explicit C(const ObjectStore&d):d_(d){}std::size_t size()const noexcept override{return d_.size();}bool contains(const ObjectId&x)const noexcept override{return d_.contains(x);}const ObjectRecord* find(const ObjectId&x)const noexcept override{++finds;return d_.find(x);}std::vector<ObjectRecord> allObjects()const override{++alls;return d_.allObjects();}std::vector<ObjectRecord> children(const std::optional<ObjectId>&p)const override{++childs;return d_.children(p);}mutable std::size_t alls=0,childs=0,finds=0;private:const ObjectStore&d_;};ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));auto before=b.allObjects();C c(b);StagedObjectView s(c);EXPECT_EQ(resolve(s,{id(1)}).final_delete_set,std::vector<ObjectId>({id(1),id(10)}));EXPECT_EQ(c.alls,1U);EXPECT_GE(c.childs,1U);EXPECT_GE(c.finds,1U);EXPECT_EQ(b.allObjects(),before); }
TEST(DeleteClosure, MultiWaveProjectionScanStillOnce){ class C final:public ObjectStore{public:explicit C(const ObjectStore&d):d_(d){}std::size_t size()const noexcept override{return d_.size();}bool contains(const ObjectId&x)const noexcept override{return d_.contains(x);}const ObjectRecord* find(const ObjectId&x)const noexcept override{++finds;return d_.find(x);}std::vector<ObjectRecord> allObjects()const override{++alls;return d_.allObjects();}std::vector<ObjectRecord> children(const std::optional<ObjectId>&p)const override{++childs;return d_.children(p);}mutable std::size_t alls=0,childs=0,finds=0;private:const ObjectStore&d_;};ReferenceObjectStore b;insert(b,shape(1));insert(b,connector(10,id(1)));insert(b,shape(2,id(10)));insert(b,connector(20,id(2)));C c(b);StagedObjectView s(c);const auto staged_before=s.allObjects();c.alls=0;auto out=resolve(s,{id(1)});EXPECT_EQ(out.requested_delete_ids,std::vector<ObjectId>({id(1)}));EXPECT_EQ(out.final_delete_set,std::vector<ObjectId>({id(1),id(2),id(10),id(20)}));EXPECT_EQ(c.alls,1U);EXPECT_GE(c.childs,4U);const auto staged_after=s.allObjects();EXPECT_EQ(staged_after,staged_before); }
TEST(DeleteClosure, IndexedIndexRemainsConsistentAfterClosure){ IndexedObjectStore indexed;insert(indexed,shape(1));insert(indexed,connector(10,id(1)));insert(indexed,shape(2,id(10)));auto before=indexed.allObjects();StagedObjectView s(indexed);auto out=resolve(s,{id(1)});EXPECT_EQ(out.final_delete_set,std::vector<ObjectId>({id(1),id(2),id(10)}));EXPECT_TRUE(internal::ObjectStoreMutator::indexMatchesRebuild(indexed));EXPECT_EQ(indexed.allObjects(),before); }
TEST(DeleteClosure, MissingAtomic){ReferenceObjectStore b;insert(b,shape(1));StagedObjectView s(b);DeleteClosure c{};c.requested_delete_ids={id(90)};c.resolved_hierarchy_closure={id(91)};c.resolved_connector_cascade_closure={id(92)};c.final_delete_set={id(93)};auto before=c;const ObjectId q[]={id(1),id(99)};EXPECT_EQ(resolveDeleteClosure(s,q,&c).issue,StatefulIssue::kObjectMissing);EXPECT_EQ(c.requested_delete_ids,before.requested_delete_ids);EXPECT_EQ(c.resolved_hierarchy_closure,before.resolved_hierarchy_closure);EXPECT_EQ(c.resolved_connector_cascade_closure,before.resolved_connector_cascade_closure);EXPECT_EQ(c.final_delete_set,before.final_delete_set);}
}}
