#include "../src/rich_text_state_plan.hpp"
#include <gtest/gtest.h>
namespace canvas::semantic { namespace {
ObjectId id(unsigned n){return ObjectId::fromUint64(n);} ParagraphStyle ps(){return {ParagraphAlignment::kLeft,1,0,0};} TextStyle ts(float c=1){TextStyle s{};s.font_resource_id=ResourceId{id(90)};s.font_size=12;s.weight=400;s.color={c,c,c,1};return s;} RichTextContent doc(){RichTextContent c;Paragraph p;p.id=id(1);p.style=ps();p.runs.push_back({"A😀B",ts()});c.document.paragraphs.push_back(p);return c;} RichTextDelta delta(std::initializer_list<RichTextStep> s){RichTextDelta d;d.delta_version=1;d.steps=s;return d;}
TEST(RichTextStatePlan,TXT_S01_UnicodeScalarInsertInAEmojiB){auto c=doc();RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),2,"X",ts()}}),&o).ok());Paragraph e=c.document.paragraphs[0];e.runs={{"A😀",ts()},{"X",ts()},{"B",ts()}};e.runs={{"A😀XB",ts()}};EXPECT_EQ(o.document.paragraphs[0].id,id(1));EXPECT_EQ(o.document.paragraphs[0].runs,e.runs);}
TEST(RichTextStatePlan,TXT_S02_DeleteAcrossRunBoundaryNormalizes){auto c=doc();auto a=ts(),b=ts(0.5f);c.document.paragraphs[0].runs={{"A",a},{"😀B",b}};RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({DeleteTextStep{id(1),0,2}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs,(std::vector<TextRun>{{"B",b}}));}
TEST(RichTextStatePlan,TXT_S03_SplitAtZero){RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(doc(),delta({SplitParagraphStep{id(1),0,id(2)}}),&o).ok());EXPECT_EQ(o.document.paragraphs.size(),2U);EXPECT_TRUE(o.document.paragraphs[0].runs.empty());EXPECT_EQ(o.document.paragraphs[1].runs,(std::vector<TextRun>{{"A😀B",ts()}}));}
TEST(RichTextStatePlan,TXT_S04_SplitAtEnd){RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(doc(),delta({SplitParagraphStep{id(1),3,id(2)}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs,(std::vector<TextRun>{{"A😀B",ts()}}));EXPECT_TRUE(o.document.paragraphs[1].runs.empty());}
TEST(RichTextStatePlan,TXT_S05_SplitParagraphIdCollisionRejects){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();c.document.paragraphs.push_back(p);auto sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({SplitParagraphStep{id(1),0,id(2)}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S06_MergeAdjacentKeepsFirstIdAndStyle){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();p.runs={{"Z",ts()}};c.document.paragraphs.push_back(p);RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({MergeParagraphStep{id(1),id(2)}}),&o).ok());EXPECT_EQ(o.document.paragraphs.size(),1U);EXPECT_EQ(o.document.paragraphs[0].id,id(1));EXPECT_EQ(o.document.paragraphs[0].runs,(std::vector<TextRun>{{"A😀BZ",ts()}}));}
TEST(RichTextStatePlan,TXT_S07_MergeNonAdjacentRejects){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();Paragraph q=p;q.id=id(3);c.document.paragraphs.push_back(p);c.document.paragraphs.push_back(q);auto sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({MergeParagraphStep{id(1),id(3)}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S08_SetInlineStyleSplitsAndMergesDeterministically){auto c=doc();auto a=ts(),b=ts(0.2f);c.document.paragraphs[0].runs={{"A😀B",a}};RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SetInlineStyleStep{id(1),1,1,b}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs,(std::vector<TextRun>{{"A",a},{"😀",b},{"B",a}}));}
TEST(RichTextStatePlan,TXT_S09_SetParagraphStyleReplacesCompleteStyle){auto c=doc();auto s=ps();s.alignment=ParagraphAlignment::kCenter;RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SetParagraphStyleStep{id(1),s}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].style,s);EXPECT_EQ(o.document.paragraphs[0].runs,c.document.paragraphs[0].runs);}
TEST(RichTextStatePlan,TXT_S10_SecondStepResolvesFirstStepStagedState){auto c=doc();auto s=ps();s.alignment=ParagraphAlignment::kRight;RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SplitParagraphStep{id(1),1,id(2)},SetParagraphStyleStep{id(2),s}}),&o).ok());EXPECT_EQ(o.document.paragraphs[1].id,id(2));EXPECT_EQ(o.document.paragraphs[1].style,s);EXPECT_EQ(o.document.paragraphs[1].runs,(std::vector<TextRun>{{"😀B",ts()}}));}
TEST(RichTextStatePlan,TXT_S11_SecondStepInvalidLeavesWholeOutputUnchanged){auto c=doc(),sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(9),0,1}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S12_EmptyParagraphCanonicalRunsRemainEmpty){auto c=doc();c.document.paragraphs[0].runs.clear();RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(1),0,1}}),&o).ok());EXPECT_EQ(o.document.paragraphs,(std::vector<Paragraph>{{id(1),ps(),{}}}));}
} }
