#include "../src/rich_text_state_plan.hpp"
#include <gtest/gtest.h>
namespace canvas::semantic { namespace {
ObjectId id(unsigned n){return ObjectId::fromUint64(n);} ParagraphStyle ps(){return {ParagraphAlignment::kLeft,1,0,0};}
TextStyle ts(float c=1){TextStyle s{};s.font_resource_id=ResourceId{id(90)};s.font_size=12;s.weight=400;s.color={c,c,c,1};return s;}
RichTextContent doc(){RichTextContent c;Paragraph p;p.id=id(1);p.style=ps();p.runs={{"A😀B",ts()}};c.document.paragraphs.push_back(p);return c;}
RichTextDelta delta(std::initializer_list<RichTextStep> s){return RichTextDelta{1,s};}
TEST(RichTextStatePlan,TXT_S01_UnicodeScalarInsertInAEmojiB){auto c=doc();RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),2,"X",ts()}}),&o).ok());auto e=c;e.document.paragraphs[0].runs={{"A😀XB",ts()}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S02_DeleteAcrossRunBoundaryNormalizes){auto c=doc();c.document.paragraphs[0].runs={{"A",ts()},{"😀B",ts(.5f)}};RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({DeleteTextStep{id(1),0,2}}),&o).ok());auto e=c;e.document.paragraphs[0].runs={{"B",ts(.5f)}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S03_SplitAtZero){RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(doc(),delta({SplitParagraphStep{id(1),0,id(2)}}),&o).ok());auto e=RichTextContent{};e.document.paragraphs={Paragraph{id(1),ps(),{}},Paragraph{id(2),ps(),{{"A😀B",ts()}}}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S04_SplitAtEnd){RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(doc(),delta({SplitParagraphStep{id(1),3,id(2)}}),&o).ok());auto e=RichTextContent{};e.document.paragraphs={Paragraph{id(1),ps(),{{"A😀B",ts()}}},Paragraph{id(2),ps(),{}}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S05_SplitParagraphIdCollisionRejects){auto c=doc();c.document.paragraphs.push_back(Paragraph{id(2),ps(),{}});auto sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({SplitParagraphStep{id(1),0,id(2)}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S06_MergeAdjacentKeepsFirstIdAndStyle){auto c=doc();c.document.paragraphs.push_back(Paragraph{id(2),ps(),{{"Z",ts()}}});RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({MergeParagraphStep{id(1),id(2)}}),&o).ok());auto e=doc();e.document.paragraphs[0].runs={{"A😀BZ",ts()}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S07_MergeNonAdjacentRejects){auto c=doc();c.document.paragraphs.push_back(Paragraph{id(2),ps(),{{"Z",ts()}}});c.document.paragraphs.push_back(Paragraph{id(3),ps(),{{"Q",ts()}}});auto sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({MergeParagraphStep{id(1),id(3)}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S08_SetInlineStyleSplitsAndMergesDeterministically){auto c=doc();auto a=ts(),b=ts(.2f);c.document.paragraphs[0].runs={{"A😀B",a}};RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SetInlineStyleStep{id(1),1,1,b}}),&o).ok());auto e=c;e.document.paragraphs[0].runs={{"A",a},{"😀",b},{"B",a}};EXPECT_EQ(o,e);auto merge=doc();merge.document.paragraphs[0].runs={{"A",a},{"😀",a},{"B",a}};RichTextContent m;ASSERT_TRUE(internal::prepareRichTextDeltaState(merge,delta({SetInlineStyleStep{id(1),1,1,a}}),&m).ok());auto merged=merge;merged.document.paragraphs[0].runs={{"A😀B",a}};EXPECT_EQ(m,merged);}
TEST(RichTextStatePlan,TXT_S09_SetParagraphStyleReplacesCompleteStyle){auto c=doc();auto s=ps();s.alignment=ParagraphAlignment::kCenter;s.spacing_after=2;RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SetParagraphStyleStep{id(1),s}}),&o).ok());auto e=c;e.document.paragraphs[0].style=s;EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S10_SecondStepResolvesFirstStepStagedState){auto c=doc();auto s=ps();s.alignment=ParagraphAlignment::kRight;RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({SplitParagraphStep{id(1),1,id(2)},SetParagraphStyleStep{id(2),s}}),&o).ok());auto e=RichTextContent{};e.document.paragraphs={Paragraph{id(1),ps(),{{"A",ts()}}},Paragraph{id(2),s,{{"😀B",ts()}}}};EXPECT_EQ(o,e);}
TEST(RichTextStatePlan,TXT_S11_SecondStepInvalidLeavesWholeOutputUnchanged){auto c=doc(),sent=doc();RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(9),0,1}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S12_EmptyParagraphCanonicalRunsRemainEmpty){auto c=doc();c.document.paragraphs[0].runs.clear();RichTextContent o;ASSERT_TRUE(internal::prepareRichTextDeltaState(c,delta({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(1),0,1}}),&o).ok());auto e=c;e.document.paragraphs[0].runs.clear();EXPECT_EQ(o,e);}
} }
