#include "../src/rich_text_state_plan.hpp"
#include <gtest/gtest.h>
namespace canvas::semantic { namespace {
ObjectId id(unsigned n){return ObjectId::fromUint64(n);} ParagraphStyle ps(){return {ParagraphAlignment::kLeft,1,0,0};} TextStyle ts(){TextStyle s{};s.font_resource_id=ResourceId{id(90)};s.font_size=12;s.weight=400;s.color={1,1,1,1};return s;} RichTextContent doc(std::string text="A😀B"){RichTextContent c;Paragraph p;p.id=id(1);p.style=ps();if(!text.empty())p.runs.push_back({text,ts()});c.document.paragraphs.push_back(p);return c;} RichTextDelta d(std::initializer_list<RichTextStep> s){RichTextDelta x;x.delta_version=1;x.steps=s;return x;}
TEST(RichTextStatePlan,TXT_S01_UnicodeScalarInsertInAEmojiB){auto c=doc();RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(c,d({InsertTextStep{id(1),2,"X",ts()}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs[0].text,"A😀XB");}
TEST(RichTextStatePlan,TXT_S02_DeleteAcrossRunBoundaryNormalizes){auto c=doc();c.document.paragraphs[0].runs={{"A",ts()},{"😀B",ts()}};RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(c,d({DeleteTextStep{id(1),0,2}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs.size(),1U);}
TEST(RichTextStatePlan,TXT_S03_SplitAtZero){RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(doc(),d({SplitParagraphStep{id(1),0,id(2)}}),&o).ok());EXPECT_TRUE(o.document.paragraphs[0].runs.empty());}
TEST(RichTextStatePlan,TXT_S04_SplitAtEnd){RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(doc(),d({SplitParagraphStep{id(1),3,id(2)}}),&o).ok());EXPECT_EQ(o.document.paragraphs.size(),2U);}
TEST(RichTextStatePlan,TXT_S05_SplitParagraphIdCollisionRejects){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();c.document.paragraphs.push_back(p);RichTextContent o=doc("sentinel");EXPECT_EQ(internal::prepareRichTextDeltaState(c,d({SplitParagraphStep{id(1),0,id(2)}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,doc("sentinel"));}
TEST(RichTextStatePlan,TXT_S06_MergeAdjacentKeepsFirstIdAndStyle){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();p.runs.push_back({"Z",ts()});c.document.paragraphs.push_back(p);RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(c,d({MergeParagraphStep{id(1),id(2)}}),&o).ok());EXPECT_EQ(o.document.paragraphs.size(),1U);EXPECT_EQ(o.document.paragraphs[0].id,id(1));}
TEST(RichTextStatePlan,TXT_S07_MergeNonAdjacentRejects){auto c=doc();Paragraph p;p.id=id(2);p.style=ps();Paragraph q=p;q.id=id(3);c.document.paragraphs.push_back(p);c.document.paragraphs.push_back(q);RichTextContent o=doc("sentinel");EXPECT_EQ(internal::prepareRichTextDeltaState(c,d({MergeParagraphStep{id(1),id(3)}}),&o).issue,StatefulIssue::kTextStateInvalid);}
TEST(RichTextStatePlan,TXT_S08_SetInlineStyleSplitsAndMergesDeterministically){RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(doc(),d({SetInlineStyleStep{id(1),1,1,ts()}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].runs.size(),1U);}
TEST(RichTextStatePlan,TXT_S09_SetParagraphStyleReplacesCompleteStyle){RichTextContent o;auto s=ps();s.alignment=ParagraphAlignment::kCenter;EXPECT_TRUE(internal::prepareRichTextDeltaState(doc(),d({SetParagraphStyleStep{id(1),s}}),&o).ok());EXPECT_EQ(o.document.paragraphs[0].style.alignment,ParagraphAlignment::kCenter);}
TEST(RichTextStatePlan,TXT_S10_SecondStepResolvesFirstStepStagedState){RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(doc(),d({SplitParagraphStep{id(1),1,id(2)},SetParagraphStyleStep{id(2),ps()}}),&o).ok());}
TEST(RichTextStatePlan,TXT_S11_SecondStepInvalidLeavesWholeOutputUnchanged){auto c=doc();auto sent=doc("sentinel");RichTextContent o=sent;EXPECT_EQ(internal::prepareRichTextDeltaState(c,d({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(9),0,1}}),&o).issue,StatefulIssue::kTextStateInvalid);EXPECT_EQ(o,sent);}
TEST(RichTextStatePlan,TXT_S12_EmptyParagraphCanonicalRunsRemainEmpty){auto c=doc("");RichTextContent o;EXPECT_TRUE(internal::prepareRichTextDeltaState(c,d({InsertTextStep{id(1),0,"X",ts()},DeleteTextStep{id(1),0,1}}),&o).ok());EXPECT_TRUE(o.document.paragraphs[0].runs.empty());}
} }
