#include <cassert>
#include <array>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>
#include <vector>
#include "canvas/semantic/snapshot.hpp"
namespace fs = std::filesystem;
static std::vector<std::uint8_t> bytes(const fs::path& p){std::ifstream i(p,std::ios::binary);return {std::istreambuf_iterator<char>(i),{}};}
static std::uint64_t fnv(const std::vector<std::uint8_t>& b){std::uint64_t v=1469598103934665603ULL;for(auto x:b){v^=x;v*=1099511628211ULL;}return v;}
static std::string text(const fs::path& p){const auto b=bytes(p);return {b.begin(),b.end()};}
static std::string sha256(const fs::path& p){const std::string command="shasum -a 256 '"+p.string()+"'";FILE* pipe=popen(command.c_str(),"r");assert(pipe);char buffer[256]{};const auto n=fread(buffer,1,sizeof(buffer)-1,pipe);assert(pclose(pipe)==0);std::istringstream in(std::string(buffer,n));std::string digest;in>>digest;return digest;}
static std::array<std::uint8_t,4> pixel(const std::vector<std::uint8_t>& b,std::size_t x,std::size_t y){const auto i=(y*256U+x)*4U;return {b[i],b[i+1U],b[i+2U],b[i+3U]};}
int main(){const fs::path root=G3_07_SOURCE_ROOT,fixture=root/"runtime/render/fixtures/g3-07/nine-kind-v1.axsnap",expected=root/"runtime/render/fixtures/g3-07/nine-kind-v1.expected.json";assert(fs::exists(fixture)&&fs::exists(expected));const auto fb=bytes(fixture);assert(fb.size()==1791U&&fnv(fb)==0xc74f5632133e9de2ULL);assert(sha256(fixture)=="b4d04c4424c50370991729bce124c48e8c822487c788de6d535e959aab27c37f");const auto decoded=canvas::semantic::SnapshotCodec::decode(fb);assert(decoded.ok()&&decoded.snapshot->objects.size()==9U);for(std::uint64_t i=0;i<9U;++i){assert(decoded.snapshot->objects[i].id==canvas::foundation::ObjectId::fromUint64(501U+i));assert(static_cast<unsigned>(decoded.snapshot->objects[i].kind)==i+1U);}const fs::path scratch=fs::temp_directory_path()/"axiom-g3-07-demo-test";std::error_code ec;fs::remove_all(scratch,ec);fs::create_directories(scratch,ec);const std::string b=G3_07_DEMO_BINARY,f=fixture.string();const fs::path a=scratch/"a",c=scratch/"c";assert(std::system((b+" --fixture '"+f+"' --output-dir '"+a.string()+"'").c_str())==0);assert(std::system((b+" --fixture '"+f+"' --output-dir '"+c.string()+"'").c_str())==0);for(const char*n:{"render.rgba","render-digest.txt","render-evidence.json"})assert(bytes(a/n)==bytes(c/n));const auto raster=bytes(a/"render.rgba");assert(raster.size()==256U*256U*4U);assert(sha256(a/"render.rgba")=="81d2314034d0fcb0152daa33f5706ac8d519c1affba9c646c2b99145bfbdf042");const auto digest=bytes(a/"render-digest.txt");const std::string digestText(digest.begin(),digest.end());assert(digestText=="fnv1a64:7b8eb8c70c65afe5\n");const auto expectedText=text(expected);assert(expectedText.find("oracle_independence")!=std::string::npos&&expectedText.find("81d2314034d0fcb0152daa33f5706ac8d519c1affba9c646c2b99145bfbdf042")!=std::string::npos);const auto magenta=std::array<std::uint8_t,4>{255,0,255,255};const auto transparent=std::array<std::uint8_t,4>{0,0,0,0};assert(pixel(raster,8,46)==magenta);assert(pixel(raster,16,46)==transparent);assert(pixel(raster,24,46)==magenta);for(std::size_t y=0;y<256U;++y)for(std::size_t x=128U;x<256U;++x)assert(pixel(raster,x,y)[3]==0U);assert(std::system((b+" --fixture '"+f+"' --output-dir '"+a.string()+"'").c_str())!=0);assert(bytes(a/"render.rgba")==raster);const auto malformed=scratch/"malformed.axsnap";std::ofstream(malformed)<<"not-a-snapshot";assert(std::system((b+" --fixture '"+malformed.string()+"' --output-dir '"+(scratch/"malformed-out").string()+"'").c_str())!=0);assert(!fs::exists(scratch/"malformed-out"));assert(std::system((b+" --fixture '"+f+"' --output-dir '"+(scratch/"missing-parent"/"out").string()+"'").c_str())!=0);assert(!fs::exists(scratch/"missing-parent"/"out"));assert(std::system((b+" --fixture '"+(scratch/"missing.axsnap").string()+"' --output-dir '"+(scratch/"missing-out").string()+"'").c_str())!=0);assert(!fs::exists(scratch/"missing-out"));fs::remove_all(scratch,ec);return 0;}
