import assert from "node:assert/strict"; import test from "node:test";
import { asActionId,asCompletionTokenId,asMessageId,asSessionId,asSourceId,asTaggedU64 } from "@axiom/platform-harness-protocol";
import { ReferencePlatformRunner,ProtocolViolation } from "@axiom/platform-harness-runner";
import { InProcessTransport,SerializedLoopbackTransport,TransportError } from "@axiom/platform-harness-transport";
import { MalformedScriptCatalog, ScriptedAdapter } from "../dist/index.js";
const env=(mode,id,type,epoch,payload)=>({protocol:"axiom-platform-harness-exec-v1",protocolVersion:1,messageId:asMessageId(id),messageType:type,sessionId:asSessionId("session:001"),sessionEpoch:asTaggedU64(epoch),payload});
const category=(fn,value)=>assert.throws(fn,e=>e instanceof ProtocolViolation&&e.divergence.category===value);
function validFlow(transport){const runner=new ReferencePlatformRunner(),adapter=new ScriptedAdapter(runner,transport);adapter.connect();adapter.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello(transport.boundaryMode)}]});runner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");const d=runner.dispatchAction({actionId:asActionId("action:001"),stepId:"step:001",commandSeq:asTaggedU64("u64:0000000000000000"),completionMode:"WAIT_FOR_ACTION_COMPLETION",action:"render",parameters:{}});adapter.run({steps:[{kind:"SEND",location:"receipt",envelope:env(transport.boundaryMode,"msg:00002","ACTION_RECEIPT","u64:0000000000000001",{actionId:"action:001",commandSeq:d.commandSeq,receiptStatus:"DISPATCHED",tokenId:"completion:001"})},{kind:"SEND",location:"completion",envelope:env(transport.boundaryMode,"msg:00003","ACTION_COMPLETION","u64:0000000000000001",{tokenId:"completion:001",actionId:"action:001",outcome:"SUCCEEDED",artifacts:[]})},{kind:"SEND",location:"source.open",envelope:env(transport.boundaryMode,"msg:00004","SOURCE_LEASE_OPEN","u64:0000000000000001",{sourceId:"source:touch"})},{kind:"SEND",location:"fence",envelope:env(transport.boundaryMode,"msg:00005","FENCE_STATUS","u64:0000000000000001",{generation:"u64:0000000000000001"})},{kind:"EVENT_DRAFT_CONTEXT",location:"event",sourceId:asSourceId("source:touch"),generation:asTaggedU64("u64:0000000000000001"),draft:{event:"POINTER",data:{x:1}}},{kind:"SEND",location:"source.close",envelope:env(transport.boundaryMode,"msg:00006","SOURCE_LEASE_CLOSE","u64:0000000000000001",{sourceId:"source:touch"})}]});runner.finalize();return runner.checkpoint();}
test("valid flow is logically equivalent across boundaries",()=>{const a=validFlow(new InProcessTransport()),b=validFlow(new SerializedLoopbackTransport());delete a.transitionTrace;delete b.transitionTrace;assert.deepEqual(a,b);});
test("script deterministically injects stale epoch",()=>{const runner=new ReferencePlatformRunner(),adapter=new ScriptedAdapter(runner,new InProcessTransport());adapter.connect();adapter.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});runner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");category(()=>adapter.run(MalformedScriptCatalog.staleEpoch("IN_PROCESS")),"STALE_SESSION_EPOCH");});
test("malformed injection differs only at boundary portability layer",()=>{const serialized=new ScriptedAdapter(new ReferencePlatformRunner(),new SerializedLoopbackTransport());serialized.connect();assert.throws(()=>serialized.run({steps:[{kind:"INJECT",location:"bad-line",bytes:new TextEncoder().encode("{}") }]}),e=>e instanceof TransportError&&e.diagnostic.category==="INVALID_JSON_LINE");});
test("malformed catalog drives duplicate completion lease leak and fault mismatch",()=>{
  const duplicateRunner=new ReferencePlatformRunner(),duplicate=new ScriptedAdapter(duplicateRunner,new InProcessTransport());duplicate.connect();duplicate.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});duplicateRunner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");const d=duplicateRunner.dispatchAction({actionId:asActionId("action:001"),stepId:"step:001",commandSeq:asTaggedU64("u64:0000000000000000"),completionMode:"WAIT_FOR_ACTION_COMPLETION",action:"render",parameters:{}});category(()=>duplicate.run(MalformedScriptCatalog.duplicateCompletion("IN_PROCESS",d.commandSeq)),"DUPLICATE_COMPLETION");
  const leakRunner=new ReferencePlatformRunner(),leak=new ScriptedAdapter(leakRunner,new InProcessTransport());leak.connect();leak.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});leakRunner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");leak.run(MalformedScriptCatalog.leaseLeak("IN_PROCESS"));category(()=>leakRunner.finalize(),"UNRESOLVED_REGISTRY");
  const faultRunner=new ReferencePlatformRunner(),fault=new ScriptedAdapter(faultRunner,new InProcessTransport());fault.connect();fault.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});faultRunner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");category(()=>fault.run(MalformedScriptCatalog.faultPulseMismatch("IN_PROCESS")),"FAULT_HANDLE_UNKNOWN");
});
test("reconnect requires HELLO and old session messages cannot revive",()=>{
  const missingRunner=new ReferencePlatformRunner(),missing=new ScriptedAdapter(missingRunner,new InProcessTransport());missing.connect();missing.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});missingRunner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");missing.run({steps:[{kind:"DISCONNECT"},{kind:"RECONNECT"}]});category(()=>missingRunner.openSession("session:002","u64:0000000000000002","adapter:scripted:001"),"PROTOCOL_VERSION_MISMATCH");
  const runner=new ReferencePlatformRunner(),adapter=new ScriptedAdapter(runner,new InProcessTransport());adapter.connect();adapter.run({steps:[{kind:"SEND",location:"hello",envelope:ScriptedAdapter.hello("IN_PROCESS")}]});runner.openSession("session:001","u64:0000000000000001","adapter:scripted:001");adapter.run({steps:[{kind:"DISCONNECT"},{kind:"RECONNECT"},{kind:"SEND",location:"hello.2",envelope:{...ScriptedAdapter.hello("IN_PROCESS","msg:00020"),sessionId:asSessionId("session:002")}}]});runner.openSession("session:002","u64:0000000000000002","adapter:scripted:001");category(()=>adapter.run(MalformedScriptCatalog.staleEpoch("IN_PROCESS")),"STALE_SESSION_EPOCH");
});
