#include "protobuf_object_mapping.hpp"

#if defined(CANVAS_SEMANTIC_PROTOBUF)
#include "auditoryworks/axiom/v1/brush_stroke.pb.h"
#include "auditoryworks/axiom/v1/connector.pb.h"
#include "auditoryworks/axiom/v1/erase_mask.pb.h"
#include "auditoryworks/axiom/v1/object.pb.h"
#include "auditoryworks/axiom/v1/paint.pb.h"
#include "auditoryworks/axiom/v1/property.pb.h"
#include "auditoryworks/axiom/v1/rich_text.pb.h"
#include "auditoryworks/axiom/v1/vector_path.pb.h"

#include <algorithm>
#include <string>

namespace canvas::semantic::internal {
namespace {
namespace p = auditoryworks::axiom::v1;

void setId(const ObjectId& source, p::Id128* destination) {
    destination->set_value(std::string(reinterpret_cast<const char*>(source.bytes.data()), source.bytes.size()));
}
bool getId(const p::Id128& source, ObjectId& destination) {
    if (!source.has_value() || source.value().size() != destination.bytes.size()) return false;
    std::copy_n(source.value().begin(), destination.bytes.size(), destination.bytes.begin());
    return true;
}
void setVec(const Vec2& source, p::Vec2* destination) { destination->set_x(source.x); destination->set_y(source.y); }
bool getVec(const p::Vec2& source, Vec2& destination) { if (!source.has_x() || !source.has_y()) return false; destination={source.x(),source.y()}; return true; }
void setColor(const ColorValue& source, p::ColorValue* destination) { destination->set_r(source.r);destination->set_g(source.g);destination->set_b(source.b);destination->set_a(source.a); }
bool getColor(const p::ColorValue& source, ColorValue& destination) { if(!source.has_r()||!source.has_g()||!source.has_b()||!source.has_a())return false; destination={source.r(),source.g(),source.b(),source.a()}; return true; }

void setGeometry(const VectorPathGeometry& source, p::VectorPathGeometry* destination) {
    destination->set_fill_rule(static_cast<p::FillRule>(source.fill_rule));
    for (const auto& command : source.commands) std::visit([destination](const auto& value) {
        using Item=std::decay_t<decltype(value)>; auto* command=destination->add_commands();
        if constexpr(std::is_same_v<Item,MoveTo>) setVec(value.point,command->mutable_move_to()->mutable_point());
        else if constexpr(std::is_same_v<Item,LineTo>) setVec(value.end,command->mutable_line_to()->mutable_end());
        else if constexpr(std::is_same_v<Item,QuadTo>) { auto* q=command->mutable_quad_to();setVec(value.control,q->mutable_control());setVec(value.end,q->mutable_end()); }
        else if constexpr(std::is_same_v<Item,CubicTo>) { auto* c=command->mutable_cubic_to();setVec(value.control1,c->mutable_control1());setVec(value.control2,c->mutable_control2());setVec(value.end,c->mutable_end()); }
        else command->mutable_close_path();
    }, command);
}
bool getGeometry(const p::VectorPathGeometry& source, VectorPathGeometry& destination) {
    if(!source.has_fill_rule())return false;
    destination.fill_rule=static_cast<FillRule>(source.fill_rule()); destination.commands.clear();
    for(const auto& command:source.commands()) switch(command.command_case()) {
      case p::PathCommand::kMoveTo:{if(!command.move_to().has_point())return false;Vec2 v;if(!getVec(command.move_to().point(),v))return false;destination.commands.emplace_back(MoveTo{v});break;}
      case p::PathCommand::kLineTo:{if(!command.line_to().has_end())return false;Vec2 v;if(!getVec(command.line_to().end(),v))return false;destination.commands.emplace_back(LineTo{v});break;}
      case p::PathCommand::kQuadTo:{if(!command.quad_to().has_control()||!command.quad_to().has_end())return false;Vec2 c,e;if(!getVec(command.quad_to().control(),c)||!getVec(command.quad_to().end(),e))return false;destination.commands.emplace_back(QuadTo{c,e});break;}
      case p::PathCommand::kCubicTo:{if(!command.cubic_to().has_control1()||!command.cubic_to().has_control2()||!command.cubic_to().has_end())return false;Vec2 c1,c2,e;if(!getVec(command.cubic_to().control1(),c1)||!getVec(command.cubic_to().control2(),c2)||!getVec(command.cubic_to().end(),e))return false;destination.commands.emplace_back(CubicTo{c1,c2,e});break;}
      case p::PathCommand::kClosePath:destination.commands.emplace_back(ClosePath{});break;
      default:return false;
    } return true;
}

void setTextStyle(const TextStyle& source,p::TextStyle* destination){if(source.font_resource_id)setId(source.font_resource_id->value,destination->mutable_font_resource_id());destination->set_font_size(source.font_size);destination->set_weight(source.weight);destination->set_italic(source.italic);destination->set_underline(source.underline);setColor(source.color,destination->mutable_color());}
bool getTextStyle(const p::TextStyle& source,TextStyle& destination){if(!source.has_font_size()||!source.has_weight()||!source.has_italic()||!source.has_underline()||!source.has_color())return false;destination.font_resource_id.reset();if(source.has_font_resource_id()){ObjectId id;if(!getId(source.font_resource_id(),id))return false;destination.font_resource_id=ResourceId{id};}destination.font_size=source.font_size();destination.weight=source.weight();destination.italic=source.italic();destination.underline=source.underline();return getColor(source.color(),destination.color);}
void setParagraphStyle(const ParagraphStyle& source,p::ParagraphStyle* destination){destination->set_alignment(static_cast<p::ParagraphAlignment>(source.alignment));destination->set_line_height(source.line_height);destination->set_spacing_before(source.spacing_before);destination->set_spacing_after(source.spacing_after);}
bool getParagraphStyle(const p::ParagraphStyle& source,ParagraphStyle& destination){if(!source.has_alignment()||!source.has_line_height()||!source.has_spacing_before()||!source.has_spacing_after())return false;destination={static_cast<ParagraphAlignment>(source.alignment()),source.line_height(),source.spacing_before(),source.spacing_after()};return true;}

void setRichText(const RichTextContent& source,p::ObjectContent* destination){auto* doc=destination->mutable_rich_text()->mutable_document();for(const auto& paragraph:source.document.paragraphs){auto* pgr=doc->add_paragraphs();setId(paragraph.id,&*pgr->mutable_paragraph_id());setParagraphStyle(paragraph.style,pgr->mutable_style());for(const auto& run:paragraph.runs){auto* r=pgr->add_runs();r->set_text(run.text);setTextStyle(run.style,r->mutable_style());}}}
bool getRichText(const p::ObjectContent& source,RichTextContent& destination){if(!source.rich_text().has_document())return false;destination.document.paragraphs.clear();for(const auto& paragraph:source.rich_text().document().paragraphs()){if(!paragraph.has_paragraph_id()||!paragraph.has_style())return false;Paragraph mapped;if(!getId(paragraph.paragraph_id(),mapped.id)||!getParagraphStyle(paragraph.style(),mapped.style))return false;for(const auto& run:paragraph.runs()){if(!run.has_text()||!run.has_style())return false;TextRun item;item.text=run.text();if(!getTextStyle(run.style(),item.style))return false;mapped.runs.push_back(std::move(item));}destination.document.paragraphs.push_back(std::move(mapped));}return true;}

void setBrush(const BrushDescriptor& source,p::BrushDescriptor* destination){destination->set_brush_family_id(source.brush_family_id);destination->set_brush_version(source.brush_version);setColor(source.color,destination->mutable_color());destination->set_nominal_size(source.nominal_size);destination->set_opacity(source.opacity);destination->mutable_pressure()->set_enabled(source.pressure.enabled);if(source.pressure.size_curve){auto* c=destination->mutable_pressure()->mutable_size_curve();for(auto point:source.pressure.size_curve->points){auto* pnt=c->add_points();pnt->set_x(point.x);pnt->set_y(point.y);}}if(source.pressure.opacity_curve){auto* c=destination->mutable_pressure()->mutable_opacity_curve();for(auto point:source.pressure.opacity_curve->points){auto* pnt=c->add_points();pnt->set_x(point.x);pnt->set_y(point.y);}}destination->mutable_tilt()->set_enabled(source.tilt.enabled);destination->mutable_tilt()->set_size_influence(source.tilt.size_influence);destination->mutable_tilt()->set_angle_influence(source.tilt.angle_influence);destination->mutable_smoothing()->set_amount(source.smoothing.amount);destination->mutable_spacing()->set_normalized_spacing(source.spacing.normalized_spacing);destination->set_blend_mode(static_cast<p::BrushBlendMode>(source.blend_mode));if(source.texture_resource_id)setId(source.texture_resource_id->value,destination->mutable_texture_resource_id());}
bool getBrush(const p::BrushDescriptor& source,BrushDescriptor& destination){if(!source.has_brush_family_id()||!source.has_brush_version()||!source.has_color()||!source.has_nominal_size()||!source.has_opacity()||!source.has_pressure()||!source.has_tilt()||!source.has_smoothing()||!source.has_spacing()||!source.has_blend_mode())return false;const auto& pressure=source.pressure();const auto& tilt=source.tilt();if(!pressure.has_enabled()||!tilt.has_enabled()||!tilt.has_size_influence()||!tilt.has_angle_influence()||!source.smoothing().has_amount()||!source.spacing().has_normalized_spacing())return false;if(pressure.has_size_curve())for(const auto& point:pressure.size_curve().points())if(!point.has_x()||!point.has_y())return false;if(pressure.has_opacity_curve())for(const auto& point:pressure.opacity_curve().points())if(!point.has_x()||!point.has_y())return false;destination.brush_family_id=source.brush_family_id();destination.brush_version=source.brush_version();if(!getColor(source.color(),destination.color))return false;destination.nominal_size=source.nominal_size();destination.opacity=source.opacity();destination.pressure.enabled=pressure.enabled();destination.pressure.size_curve.reset();destination.pressure.opacity_curve.reset();if(pressure.has_size_curve()){PiecewiseLinearCurve01 c;for(auto point:pressure.size_curve().points())c.points.push_back({point.x(),point.y()});destination.pressure.size_curve=c;}if(pressure.has_opacity_curve()){PiecewiseLinearCurve01 c;for(auto point:pressure.opacity_curve().points())c.points.push_back({point.x(),point.y()});destination.pressure.opacity_curve=c;}destination.tilt={tilt.enabled(),tilt.size_influence(),tilt.angle_influence()};destination.smoothing={source.smoothing().amount()};destination.spacing={source.spacing().normalized_spacing()};destination.blend_mode=static_cast<BrushBlendMode>(source.blend_mode());destination.texture_resource_id.reset();if(source.has_texture_resource_id()){ObjectId id;if(!getId(source.texture_resource_id(),id))return false;destination.texture_resource_id=ResourceId{id};}return true;}
void setStroke(const StrokeRecord& source,p::StrokeRecord* destination){setBrush(source.brush,destination->mutable_brush());destination->set_deterministic_seed(source.deterministic_seed);std::visit([destination](const auto& data){using Item=std::decay_t<decltype(data)>;if constexpr(std::is_same_v<Item,VectorStrokeData>){auto* vector=destination->mutable_vector();for(auto sample:data.samples){auto* s=vector->add_samples();setVec(sample.position,s->mutable_position());s->set_pressure(sample.pressure);setVec(sample.tilt,s->mutable_tilt());}}else{auto* d=destination->mutable_dab();for(auto dab:data.dabs){auto* x=d->add_dabs();setVec(dab.center,x->mutable_center());x->set_size(dab.size);x->set_rotation(dab.rotation);x->set_opacity(dab.opacity);}}},source.data);}
bool getStroke(const p::StrokeRecord& source,StrokeRecord& destination){if(!source.has_brush()||!source.has_deterministic_seed())return false;if(!getBrush(source.brush(),destination.brush))return false;destination.deterministic_seed=source.deterministic_seed();if(source.has_vector()){VectorStrokeData data;for(auto sample:source.vector().samples()){if(!sample.has_position()||!sample.has_pressure()||!sample.has_tilt())return false;Vec2 p,t;if(!getVec(sample.position(),p)||!getVec(sample.tilt(),t))return false;data.samples.push_back({p,sample.pressure(),t});}destination.data=data;}else if(source.has_dab()){DabStrokeData data;for(auto dab:source.dab().dabs()){if(!dab.has_center()||!dab.has_size()||!dab.has_rotation()||!dab.has_opacity())return false;Vec2 p;if(!getVec(dab.center(),p))return false;data.dabs.push_back({p,dab.size(),dab.rotation(),dab.opacity()});}destination.data=data;}else return false;return true;}

void setFill(const FillStyleValue& source, p::FillStyleValue* destination) { std::visit([destination](const auto& value){using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,NoFill>) destination->mutable_none(); else {auto*s=destination->mutable_solid();setColor(value.color,s->mutable_color());}},source); }
bool getFill(const p::FillStyleValue& source, FillStyleValue& destination) { if(source.has_none()){destination=NoFill{};return true;} if(source.has_solid()&&source.solid().has_color()){ColorValue c;if(!getColor(source.solid().color(),c))return false;destination=SolidFill{c};return true;}return false; }
void setJoin(const StrokeJoin& source,p::StrokeJoin* destination){std::visit([destination](const auto& value){using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,MiterJoin>)destination->mutable_miter()->set_limit(value.limit);else if constexpr(std::is_same_v<T,RoundJoin>)destination->mutable_round();else destination->mutable_bevel();},source);}
bool getJoin(const p::StrokeJoin& source,StrokeJoin& destination){if(source.has_miter()){if(!source.miter().has_limit())return false;destination=MiterJoin{source.miter().limit()};return true;}if(source.has_round()){destination=RoundJoin{};return true;}if(source.has_bevel()){destination=BevelJoin{};return true;}return false;}
void setDash(const StrokeDash& source,p::StrokeDash* destination){std::visit([destination](const auto& value){using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,SolidDash>)destination->mutable_solid();else{auto*d=destination->mutable_pattern();for(double x:value.segments)d->add_segments(x);d->set_offset(value.offset);}},source);}
bool getDash(const p::StrokeDash& source,StrokeDash& destination){if(source.has_solid()){destination=SolidDash{};return true;}if(source.has_pattern()){if(!source.pattern().has_offset())return false;DashPattern d;d.offset=source.pattern().offset();d.segments.assign(source.pattern().segments().begin(),source.pattern().segments().end());destination=std::move(d);return true;}return false;}
void setStrokeStyle(const StrokeStyleValue& source,p::StrokeStyleValue* destination){std::visit([destination](const auto& value){using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,NoStroke>)destination->mutable_none();else{auto*s=destination->mutable_solid();setColor(value.color,s->mutable_color());s->set_width(value.width);s->set_cap(static_cast<p::StrokeCap>(value.cap));setJoin(value.join,s->mutable_join());setDash(value.dash,s->mutable_dash());}},source);}
bool getStrokeStyle(const p::StrokeStyleValue& source,StrokeStyleValue& destination){if(source.has_none()){destination=NoStroke{};return true;}if(!source.has_solid()||!source.solid().has_color()||!source.solid().has_join()||!source.solid().has_dash()||!source.solid().has_width()||!source.solid().has_cap())return false;ColorValue c;if(!getColor(source.solid().color(),c))return false;StrokeJoin j;if(!getJoin(source.solid().join(),j))return false;StrokeDash d;if(!getDash(source.solid().dash(),d))return false;destination=SolidStroke{c,source.solid().width(),static_cast<StrokeCap>(source.solid().cap()),std::move(j),std::move(d)};return true;}
bool setProperty(const PropertyValue& source,p::PropertyValue* destination){return std::visit([destination](const auto& value){using Item=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<Item,bool>)destination->set_bool_value(value);else if constexpr(std::is_same_v<Item,float>)destination->set_f32_value(value);else if constexpr(std::is_same_v<Item,ColorValue>)setColor(value,destination->mutable_color_value());else if constexpr(std::is_same_v<Item,FillStyleValue>)setFill(value,destination->mutable_fill_style());else if constexpr(std::is_same_v<Item,StrokeStyleValue>)setStrokeStyle(value,destination->mutable_stroke_style());else if constexpr(std::is_same_v<Item,BlendModeValue>)destination->set_blend_mode(static_cast<p::BlendModeValue>(value));else if constexpr(std::is_same_v<Item,ConnectorDecorationValue>)destination->set_connector_decoration(static_cast<p::ConnectorDecorationValue>(value));else return false;return true;},source);}
bool getProperty(const p::PropertyValue& source,PropertyValue& destination){switch(source.value_case()){case p::PropertyValue::kBoolValue:destination=source.bool_value();return true;case p::PropertyValue::kF32Value:destination=source.f32_value();return true;case p::PropertyValue::kColorValue:{ColorValue c;if(!getColor(source.color_value(),c))return false;destination=c;return true;}case p::PropertyValue::kFillStyle:{FillStyleValue v;if(!getFill(source.fill_style(),v))return false;destination=std::move(v);return true;}case p::PropertyValue::kStrokeStyle:{StrokeStyleValue v;if(!getStrokeStyle(source.stroke_style(),v))return false;destination=std::move(v);return true;}case p::PropertyValue::kBlendMode:destination=static_cast<BlendModeValue>(source.blend_mode());return true;case p::PropertyValue::kConnectorDecoration:destination=static_cast<ConnectorDecorationValue>(source.connector_decoration());return true;default:return false;}}
void setEndpoint(const ConnectorEndpoint& source,p::ConnectorEndpoint* destination){std::visit([destination](const auto& value){using T=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<T,FreePointEndpoint>){setVec(value.point,destination->mutable_free_point()->mutable_point());}else{auto*a=destination->mutable_attached();setId(value.target_object_id,a->mutable_target_object_id());std::visit([a](const auto& anchor){using A=std::decay_t<decltype(anchor)>;if constexpr(std::is_same_v<A,AutoPerimeterAnchor>){auto*x=a->mutable_anchor()->mutable_auto_perimeter();if(anchor.hint)setVec(*anchor.hint,x->mutable_hint());}else a->mutable_anchor()->mutable_stable_port()->set_port_id(anchor.port_id);},value.anchor);}},source.value);}
bool getEndpoint(const p::ConnectorEndpoint& source,ConnectorEndpoint& destination){if(source.has_free_point()){if(!source.free_point().has_point())return false;Vec2 p;if(!getVec(source.free_point().point(),p))return false;destination.value=FreePointEndpoint{p};return true;}if(!source.has_attached()||!source.attached().has_target_object_id()||!source.attached().has_anchor())return false;ObjectId id;if(!getId(source.attached().target_object_id(),id))return false;const auto&a=source.attached().anchor();if(a.has_auto_perimeter()){std::optional<Vec2> hint;if(a.auto_perimeter().has_hint()){Vec2 h;if(!getVec(a.auto_perimeter().hint(),h))return false;hint=h;}destination.value=AttachedEndpoint{id,AutoPerimeterAnchor{hint}};return true;}if(a.has_stable_port()){if(!a.stable_port().has_port_id())return false;destination.value=AttachedEndpoint{id,StablePortAnchor{a.stable_port().port_id()}};return true;}return false;}
}

bool toProtobufObjectRecord(const ObjectRecord& source, p::ObjectRecord& destination) {
    if (source.id.isZero() || !isKnownObjectKind(source.kind) || !source.placement.order_key.isValid()) return false;
    setId(source.id,destination.mutable_id());destination.set_kind_id(static_cast<std::uint32_t>(source.kind));destination.set_kind_version(source.kind_version);
    if(source.placement.parent_id) {
        setId(*source.placement.parent_id,destination.mutable_placement()->mutable_parent_id());
    }
    destination.mutable_placement()->mutable_order_key()->set_value(std::string(reinterpret_cast<const char*>(source.placement.order_key.bytes().data()),source.placement.order_key.bytes().size()));
    auto* t=destination.mutable_transform();t->set_a(source.transform.a);t->set_b(source.transform.b);t->set_c(source.transform.c);t->set_d(source.transform.d);t->set_tx(source.transform.tx);t->set_ty(source.transform.ty);
    auto* bag=destination.mutable_properties();for(const auto& entry:source.properties.entries){auto* item=bag->add_entries();item->set_field_id(entry.field_id);if(!setProperty(entry.value,item->mutable_value()))return false;}
    auto* content=destination.mutable_content();std::visit([content](const auto& value){using Item=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<Item,ShapeContent>){auto* x=content->mutable_shape();x->set_shape_kind(value.shape_kind);x->set_width(value.width);x->set_height(value.height);}else if constexpr(std::is_same_v<Item,ImageContent>){auto*x=content->mutable_image();setId(value.resource_id.value,x->mutable_resource_id());x->set_intrinsic_width(value.intrinsic_width);x->set_intrinsic_height(value.intrinsic_height);if(value.source_rect){auto*r=x->mutable_source_rect();r->set_x(value.source_rect->x);r->set_y(value.source_rect->y);r->set_width(value.source_rect->width);r->set_height(value.source_rect->height);}x->set_content_mode(static_cast<p::ImageContentMode>(value.content_mode));x->set_width(value.width);x->set_height(value.height);}else if constexpr(std::is_same_v<Item,VectorPathContent>)setGeometry(value.geometry,content->mutable_vector_path()->mutable_geometry());else if constexpr(std::is_same_v<Item,RichTextContent>)setRichText(value,content);else if constexpr(std::is_same_v<Item,VectorStrokeContent>)setStroke(value.stroke,content->mutable_vector_stroke()->mutable_stroke());else if constexpr(std::is_same_v<Item,DabStrokeContent>)setStroke(value.stroke,content->mutable_dab_stroke()->mutable_stroke());else if constexpr(std::is_same_v<Item,ConnectorContent>){auto*c=content->mutable_connector();setEndpoint(value.start,c->mutable_start());setEndpoint(value.end,c->mutable_end());c->set_routing(static_cast<p::ConnectorRouting>(value.routing));}else if constexpr(std::is_same_v<Item,StickyContent>){content->mutable_sticky()->set_width(value.width);content->mutable_sticky()->set_height(value.height);}else content->mutable_group();},source.content);
    for(const auto& mask:source.erase_masks){auto* m=destination.add_erase_masks();setId(mask.id,m->mutable_mask_id());auto*g=m->mutable_geometry();std::visit([g](const auto& value){using Item=std::decay_t<decltype(value)>;if constexpr(std::is_same_v<Item,SweptCircleMask>){auto*s=g->mutable_swept_circle();for(auto segment:value.segments){auto*x=s->add_segments();setVec(segment.p0.position,x->mutable_p0()->mutable_position());x->mutable_p0()->set_radius(segment.p0.radius);setVec(segment.p1.position,x->mutable_p1()->mutable_position());x->mutable_p1()->set_radius(segment.p1.radius);setVec(segment.control1,x->mutable_control1());setVec(segment.control2,x->mutable_control2());}}else setGeometry(value.path,g->mutable_filled_path()->mutable_path());},mask.geometry);}
    return true;
}

bool fromProtobufObjectRecord(const p::ObjectRecord& source, ObjectRecord& destination) {
    if(!source.has_id()||!source.has_kind_id()||!source.has_kind_version()||!source.has_placement()||!source.has_transform()||!source.has_properties()||!source.has_content())return false;
    if(!getId(source.id(),destination.id)||destination.id.isZero()||!isKnownObjectKind(static_cast<ObjectKind>(source.kind_id())))return false;
    destination.kind=static_cast<ObjectKind>(source.kind_id()); destination.kind_version=source.kind_version(); destination.placement.parent_id.reset();
    if(source.placement().has_parent_id()){ObjectId parent;if(!getId(source.placement().parent_id(),parent))return false;destination.placement.parent_id=parent;}
    if(!source.placement().has_order_key()||!source.placement().order_key().has_value())return false;
    destination.placement.order_key=OrderKey({source.placement().order_key().value().begin(),source.placement().order_key().value().end()});
    if(!destination.placement.order_key.isValid())return false;
    if(!source.transform().has_a()||!source.transform().has_b()||!source.transform().has_c()||!source.transform().has_d()||!source.transform().has_tx()||!source.transform().has_ty())return false;
    destination.transform={source.transform().a(),source.transform().b(),source.transform().c(),source.transform().d(),source.transform().tx(),source.transform().ty()};
    destination.properties.entries.clear(); for(const auto& item:source.properties().entries()){if(!item.has_field_id()||!item.has_value())return false;PropertyValue value;if(!getProperty(item.value(),value))return false;destination.properties.entries.push_back({item.field_id(),std::move(value)});}
    switch(source.content().value_case()){
      case p::ObjectContent::kShape:{const auto& x=source.content().shape();if(!x.has_shape_kind()||!x.has_width()||!x.has_height())return false;destination.content=ShapeContent{x.shape_kind(),x.width(),x.height()};break;}
      case p::ObjectContent::kImage:{const auto&x=source.content().image();if(!x.has_resource_id()||!x.has_intrinsic_width()||!x.has_intrinsic_height()||!x.has_content_mode()||!x.has_width()||!x.has_height())return false;if(x.has_source_rect()&&(!x.source_rect().has_x()||!x.source_rect().has_y()||!x.source_rect().has_width()||!x.source_rect().has_height()))return false;ObjectId id;if(!getId(x.resource_id(),id))return false;destination.content=ImageContent{ResourceId{id},x.intrinsic_width(),x.intrinsic_height(),x.has_source_rect()?std::optional<NormalizedRect>(NormalizedRect{x.source_rect().x(),x.source_rect().y(),x.source_rect().width(),x.source_rect().height()}):std::nullopt,static_cast<ImageContentMode>(x.content_mode()),x.width(),x.height()};break;}
      case p::ObjectContent::kVectorPath:{if(!source.content().vector_path().has_geometry())return false;VectorPathGeometry g;if(!getGeometry(source.content().vector_path().geometry(),g))return false;destination.content=VectorPathContent{std::move(g)};break;}
      case p::ObjectContent::kRichText:{RichTextContent x;if(!getRichText(source.content(),x))return false;destination.content=std::move(x);break;}
      case p::ObjectContent::kVectorStroke:{if(!source.content().vector_stroke().has_stroke())return false;StrokeRecord x;if(!getStroke(source.content().vector_stroke().stroke(),x))return false;destination.content=VectorStrokeContent{std::move(x)};break;}
      case p::ObjectContent::kDabStroke:{if(!source.content().dab_stroke().has_stroke())return false;StrokeRecord x;if(!getStroke(source.content().dab_stroke().stroke(),x))return false;destination.content=DabStrokeContent{std::move(x)};break;}
      case p::ObjectContent::kConnector:{ConnectorContent x;if(!source.content().connector().has_start()||!source.content().connector().has_end()||!source.content().connector().has_routing()||!getEndpoint(source.content().connector().start(),x.start)||!getEndpoint(source.content().connector().end(),x.end))return false;x.routing=static_cast<ConnectorRouting>(source.content().connector().routing());destination.content=std::move(x);break;}
      case p::ObjectContent::kSticky:{const auto& x=source.content().sticky();if(!x.has_width()||!x.has_height())return false;destination.content=StickyContent{x.width(),x.height()};break;}
      case p::ObjectContent::kGroup: destination.content=GroupContent{}; break;
      default:return false;
    }
    destination.erase_masks.clear();
    for(const auto& item:source.erase_masks()){EraseMaskRecord mask;if(!item.has_mask_id()||!getId(item.mask_id(),mask.id)||!item.has_geometry())return false;switch(item.geometry().geometry_case()){case p::EraseMaskGeometry::kSweptCircle:{SweptCircleMask geometry;for(const auto& segment:item.geometry().swept_circle().segments()){if(!segment.has_p0()||!segment.has_p1()||!segment.has_control1()||!segment.has_control2()||!segment.p0().has_position()||!segment.p0().has_radius()||!segment.p1().has_position()||!segment.p1().has_radius())return false;EraseCubicSegment out;if(!getVec(segment.p0().position(),out.p0.position)||!getVec(segment.p1().position(),out.p1.position)||!getVec(segment.control1(),out.control1)||!getVec(segment.control2(),out.control2))return false;out.p0.radius=segment.p0().radius();out.p1.radius=segment.p1().radius();geometry.segments.push_back(std::move(out));}mask.geometry=std::move(geometry);break;}case p::EraseMaskGeometry::kFilledPath:{if(!item.geometry().filled_path().has_path())return false;VectorPathGeometry g;if(!getGeometry(item.geometry().filled_path().path(),g))return false;mask.geometry=FilledPathMask{std::move(g)};break;}default:return false;}destination.erase_masks.push_back(std::move(mask));}
    return true;
}

bool roundTripProtobufObjectRecord(const ObjectRecord& source, ObjectRecord& destination) {
    p::ObjectRecord wire;
    return toProtobufObjectRecord(source, wire) && fromProtobufObjectRecord(wire, destination);
}

} // namespace canvas::semantic::internal
#endif
