#!/usr/bin/env python3
"""Create a deterministic, self-contained Canvas Skia SDK ZIP."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import zipfile

from sdk import (
    DEFAULT_PROFILE, SDK_FORMAT, SKIA_ROOT, canonical_sha256, file_sha256,
    load_profile, make_identity, module_headers, normalized_args_text, target_definition,
)


LICENSES = {
    "Skia.txt": "LICENSE",
    "FreeType.txt": "third_party/externals/freetype/LICENSE.TXT",
    "libpng.txt": "third_party/externals/libpng/LICENSE",
    "zlib.txt": "third_party/externals/zlib/LICENSE",
}
FONT = "resources/fonts/Roboto-Regular.ttf"
FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)


def cmake_config(libraries: list[str], platform: str) -> str:
    lines = [
        "# Generated by the Canvas Skia SDK producer. Do not edit.",
        "get_filename_component(_CANVAS_SKIA_PREFIX \"${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)",
        "if(TARGET CanvasSkia::Skia)",
        "  return()",
        "endif()",
    ]
    archive_targets: list[str] = []
    for index, library in enumerate(libraries):
        name = f"CanvasSkia::Archive{index}"
        archive_targets.append(name)
        lines.extend([
            f"add_library({name} STATIC IMPORTED)",
            f"set_target_properties({name} PROPERTIES",
            f"  IMPORTED_LOCATION \"${{_CANVAS_SKIA_PREFIX}}/lib/{library}\"",
            ")",
        ])
    if platform in {"macos", "ios", "ios-simulator"}:
        frameworks = ["CoreFoundation", "CoreGraphics", "CoreText", "Foundation", "Metal"]
        if platform == "macos":
            frameworks += ["AppKit", "ApplicationServices", "OpenGL"]
        else:
            frameworks += ["ImageIO", "MobileCoreServices", "UIKit"]
        for framework in frameworks:
            upper = framework.upper()
            lines.append(f"find_library(_CANVAS_SKIA_{upper} {framework} REQUIRED)")
            archive_targets.append(f"${{_CANVAS_SKIA_{upper}}}")
    elif platform == "android":
        archive_targets += ["android", "EGL", "GLESv2", "log", "dl"]
    elif platform == "windows":
        archive_targets += [
            "d3d12", "dxgi", "d3dcompiler", "ole32", "oleaut32", "fontsub",
            "user32", "usp10",
        ]
    links = ";".join(archive_targets)
    lines.extend([
        "add_library(CanvasSkia::Skia INTERFACE IMPORTED)",
        "set_target_properties(CanvasSkia::Skia PROPERTIES",
        "  INTERFACE_INCLUDE_DIRECTORIES \"${_CANVAS_SKIA_PREFIX}\"",
        f"  INTERFACE_LINK_LIBRARIES \"{links}\"",
        ")",
        "set(CanvasSkia_SDK_ROOT \"${_CANVAS_SKIA_PREFIX}\")",
        "set(CanvasSkia_FONT_PATH \"${_CANVAS_SKIA_PREFIX}/resources/fonts/Roboto-Regular.ttf\")",
        "set(CanvasSkia_MANIFEST_PATH \"${_CANVAS_SKIA_PREFIX}/manifest.json\")",
        "unset(_CANVAS_SKIA_PREFIX)",
        "",
    ])
    return "\n".join(lines)


def copy_file(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise RuntimeError(f"required SDK input is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)


def copy_library(source: Path, destination: Path, platform: str) -> None:
    if platform not in {"ios", "ios-simulator"}:
        copy_file(source, destination)
        return
    if not source.is_file():
        raise RuntimeError(f"required SDK input is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    info = subprocess.check_output(
        ["xcrun", "lipo", "-info", str(source)], text=True,
        stderr=subprocess.STDOUT,
    )
    if "Non-fat file" in info:
        copy_file(source, destination)
        return
    subprocess.run(
        ["xcrun", "lipo", str(source), "-thin", "arm64", "-output", str(destination)],
        check=True,
    )


def role(path: str) -> str:
    if path.startswith(("include/", "modules/")):
        return "header"
    if path.startswith("lib/cmake/"):
        return "cmake"
    if path.startswith("lib/"):
        return "library"
    if path.startswith("licenses/"):
        return "license"
    if path.startswith("resources/fonts/"):
        return "font"
    if path == "args.gn":
        return "build-arguments"
    raise RuntimeError(f"unclassified SDK payload: {path}")


def write_zip(root: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    if temporary.exists():
        temporary.unlink()
    with zipfile.ZipFile(
        temporary, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9,
    ) as archive:
        payload = (item for item in root.rglob("*") if item.is_file())
        for path in sorted(payload, key=lambda item: item.relative_to(root).as_posix()):
            relative = path.relative_to(root).as_posix()
            info = zipfile.ZipInfo(relative, FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            info.create_system = 3
            archive.writestr(info, path.read_bytes(), compress_type=zipfile.ZIP_DEFLATED,
                             compresslevel=9)
    temporary.replace(output)


def package(
    target_name: str, profile_path: Path, skia_root: Path,
    toolchain_path: Path, output_dir: Path,
) -> Path:
    profile = load_profile(profile_path)
    target = target_definition(profile, target_name)
    toolchain = json.loads(toolchain_path.read_text(encoding="utf-8"))
    identity = make_identity(
        profile, target_name, toolchain, profile_path=profile_path,
    )
    output_name = target["output_name"]
    build_dir = skia_root / "out" / output_name
    revision_marker = skia_root / ".canvas-poc-revision"
    revision = (
        revision_marker.read_text(encoding="utf-8").strip()
        if revision_marker.exists() else ""
    )
    if revision and revision != profile["skia_commit"]:
        raise RuntimeError("Skia checkout revision does not match the SDK profile")

    with tempfile.TemporaryDirectory(prefix=f"canvas-skia-{target_name}-") as temporary:
        stage = Path(temporary) / "sdk"
        shutil.copytree(skia_root / "include", stage / "include")
        for header in module_headers(profile):
            copy_file(skia_root / header, stage / header)
        copy_file(skia_root / FONT, stage / FONT)
        for destination, source in LICENSES.items():
            copy_file(skia_root / source, stage / "licenses" / destination)
        for library in target["libraries"]:
            copy_library(
                build_dir / library, stage / "lib" / library, target["platform"],
            )
        config = stage / "lib/cmake/CanvasSkia/CanvasSkiaConfig.cmake"
        config.parent.mkdir(parents=True, exist_ok=True)
        config.write_bytes(
            cmake_config(target["libraries"], target["platform"]).encode("utf-8")
        )
        (stage / "args.gn").write_bytes(
            normalized_args_text(profile, target_name).encode("utf-8")
        )

        files = []
        payload = (item for item in stage.rglob("*") if item.is_file())
        for path in sorted(payload, key=lambda item: item.relative_to(stage).as_posix()):
            relative = path.relative_to(stage).as_posix()
            files.append({
                "path": relative,
                "sha256": file_sha256(path),
                "size": path.stat().st_size,
                "role": role(relative),
            })
        manifest = {
            "schema_version": 1,
            "format": SDK_FORMAT,
            "sdk_id": canonical_sha256(identity),
            "identity": identity,
            "files": files,
        }
        (stage / "manifest.json").write_bytes(
            (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
        )
        asset = output_dir / f"skia-sdk-{target_name}.zip"
        write_zip(stage, asset)
    print(json.dumps({
        "asset": str(asset),
        "sha256": file_sha256(asset),
        "sdk_id": manifest["sdk_id"],
        "target": target_name,
    }, sort_keys=True))
    return asset


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--skia-root", type=Path, default=SKIA_ROOT)
    parser.add_argument("--toolchain-json", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    package(
        args.target, args.profile.resolve(), args.skia_root.resolve(),
        args.toolchain_json.resolve(), args.output.resolve(),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
