#!/usr/bin/env python3
"""Create a deterministic, self-contained Canvas Skia SDK ZIP."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile

from sdk import (
    DEFAULT_PROFILE, FULL_SDK_FORMAT, ROOT, SDK_FORMAT, SKIA_ROOT,
    canonical_sha256, file_sha256, load_profile, make_identity,
    normalized_args_text, output_name, target_definition,
)


LICENSES = {
    "Skia.txt": "LICENSE",
    "FreeType.txt": "third_party/externals/freetype/LICENSE.TXT",
    "libpng.txt": "third_party/externals/libpng/LICENSE",
    "zlib.txt": "third_party/externals/zlib/LICENSE",
}
FONT = "resources/fonts/Roboto-Regular.ttf"
MODULE_HEADERS = (
    "modules/skcms/skcms.h",
    "modules/skcms/src/skcms_public.h",
)
FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)


def cmake_config(
    libraries: list[str], platform: str, *, cjk_font: bool = False,
    icu_data: bool = False, full: bool = False,
) -> str:
    lines = [
        "# Generated by the Canvas Skia SDK producer. Do not edit.",
        "get_filename_component(_CANVAS_SKIA_PREFIX \"${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)",
        "if(TARGET CanvasSkia::Skia)",
        "  return()",
        "endif()",
    ]
    archive_targets: list[str] = []
    for index, library in enumerate(libraries):
        name = f"CanvasSkia::Archive{index}"
        archive_targets.append(name)
        lines.extend([
            f"add_library({name} STATIC IMPORTED)",
            f"set_target_properties({name} PROPERTIES",
            f"  IMPORTED_LOCATION \"${{_CANVAS_SKIA_PREFIX}}/lib/{library}\"",
            ")",
        ])
    if platform in {"macos", "ios", "ios-simulator"}:
        frameworks = ["CoreFoundation", "CoreGraphics", "CoreText", "Foundation", "Metal"]
        if platform == "macos":
            frameworks += ["AppKit", "ApplicationServices", "OpenGL"]
        else:
            frameworks += ["ImageIO", "MobileCoreServices", "UIKit"]
        for framework in frameworks:
            upper = framework.upper()
            lines.append(f"find_library(_CANVAS_SKIA_{upper} {framework} REQUIRED)")
            archive_targets.append(f"${{_CANVAS_SKIA_{upper}}}")
    elif platform == "android":
        archive_targets += ["android", "EGL", "GLESv2", "log", "dl"]
    elif platform == "windows":
        archive_targets += [
            "d3d12", "dxgi", "d3dcompiler", "ole32", "oleaut32", "fontsub",
            "user32", "usp10",
        ]
    links = ";".join(archive_targets)
    lines.extend([
        "add_library(CanvasSkia::Skia INTERFACE IMPORTED)",
        "set_target_properties(CanvasSkia::Skia PROPERTIES",
        "  INTERFACE_INCLUDE_DIRECTORIES \"${_CANVAS_SKIA_PREFIX}\"",
        f"  INTERFACE_LINK_LIBRARIES \"{links}\"",
        ")",
        "set(CanvasSkia_SDK_ROOT \"${_CANVAS_SKIA_PREFIX}\")",
        "set(CanvasSkia_FONT_PATH \"${_CANVAS_SKIA_PREFIX}/resources/fonts/Roboto-Regular.ttf\")",
        "set(CanvasSkia_MANIFEST_PATH \"${_CANVAS_SKIA_PREFIX}/manifest.json\")",
    ])
    if full:
        lines.extend([
            "set(CanvasSkia_VARIANT \"@CANVAS_SKIA_VARIANT@\")",
            "set(CanvasSkia_CAPABILITIES \"ganesh;pdf;svg;skottie;pathops;richtext;jpeg;webp;png;freetype;harfbuzz;icu\")",
        ])
        definitions = {
            "Paragraph": "SK_ENABLE_PARAGRAPH",
            "Skottie": "SK_ENABLE_SKOTTIE;SK_ENABLE_SKOTTIE_SKSLEFFECT",
            "Svg": "SK_ENABLE_SVG",
            "PathOps": "",
            "Media": "SK_CODEC_DECODES_JPEG;SK_CODEC_ENCODES_JPEG;SK_CODEC_DECODES_WEBP;SK_CODEC_ENCODES_WEBP",
        }
        for capability, compile_definitions in definitions.items():
            lines.extend([
                f"add_library(CanvasSkia::{capability} INTERFACE IMPORTED)",
                f"set_target_properties(CanvasSkia::{capability} PROPERTIES",
                "  INTERFACE_LINK_LIBRARIES \"CanvasSkia::Skia\"",
            ])
            if compile_definitions:
                lines.append(
                    f"  INTERFACE_COMPILE_DEFINITIONS \"{compile_definitions}\"",
                )
            lines.append(")")
    if cjk_font:
        lines.append(
            "set(CanvasSkia_CJK_FONT_PATH \"${_CANVAS_SKIA_PREFIX}/resources/fonts/NotoSansCJK-VF-subset.otf.ttc\")",
        )
    if icu_data:
        lines.append(
            "set(CanvasSkia_ICU_DATA_PATH \"${_CANVAS_SKIA_PREFIX}/runtime/windows/icudtl.dat\")",
        )
    lines.extend(["unset(_CANVAS_SKIA_PREFIX)", ""])
    return "\n".join(lines)


def load_archive_closure(build_dir: Path, platform: str) -> list[tuple[Path, str]]:
    closure_path = build_dir / "canvas-skia-archive-closure.json"
    if not closure_path.is_file():
        raise RuntimeError(
            "full SDK archive closure is missing; rerun tools/skia/build.py for "
            f"{build_dir.name}"
        )
    closure = json.loads(closure_path.read_text(encoding="utf-8"))
    if set(closure) != {"schema_version", "archives"} or closure["schema_version"] != 1:
        raise RuntimeError("full SDK archive closure has an unsupported schema")
    archives = closure["archives"]
    if not isinstance(archives, list) or not archives or \
       len(archives) != len(set(archives)):
        raise RuntimeError("full SDK archive closure must be an ordered unique array")
    suffix = ".lib" if platform == "windows" else ".a"
    result: list[tuple[Path, str]] = []
    packaged_names: set[str] = set()
    for value in archives:
        relative = Path(value)
        if not isinstance(value, str) or not value or relative.is_absolute() or \
           ".." in relative.parts or relative.suffix.lower() != suffix:
            raise RuntimeError(f"unsafe or mismatched archive closure path: {value!r}")
        source = build_dir / relative
        if not source.is_file():
            raise RuntimeError(f"archive closure input is missing: {source}")
        packaged = relative.as_posix().replace("/", "__")
        if packaged in packaged_names:
            raise RuntimeError(f"archive closure has a packaged-name collision: {packaged}")
        packaged_names.add(packaged)
        result.append((source, packaged))
    return result


def copy_file(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise RuntimeError(f"required SDK input is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)


def download_locked_file(url: str, sha256: str, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url) as response:
        data = response.read()
    if hashlib.sha256(data).hexdigest() != sha256:
        raise RuntimeError(f"locked download checksum mismatch: {url}")
    destination.write_bytes(data)


def copy_library(source: Path, destination: Path, platform: str) -> None:
    if platform not in {"ios", "ios-simulator"}:
        copy_file(source, destination)
        return
    if not source.is_file():
        raise RuntimeError(f"required SDK input is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    info = subprocess.check_output(
        ["xcrun", "lipo", "-info", str(source)], text=True,
        stderr=subprocess.STDOUT,
    )
    if "Non-fat file" in info:
        copy_file(source, destination)
        return
    subprocess.run(
        ["xcrun", "lipo", str(source), "-thin", "arm64", "-output", str(destination)],
        check=True,
    )


def role(path: str) -> str:
    if path.startswith(("include/", "modules/", "src/")):
        return "header"
    if path.startswith("lib/cmake/"):
        return "cmake"
    if path.startswith("lib/"):
        return "library"
    if path.startswith("licenses/"):
        return "license"
    if path.startswith("resources/fonts/"):
        return "font"
    if path.startswith("runtime/"):
        return "runtime"
    if path == "args.gn":
        return "build-arguments"
    if path == "symbols.json":
        return "symbols-metadata"
    raise RuntimeError(f"unclassified SDK payload: {path}")


def write_zip(root: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    if temporary.exists():
        temporary.unlink()
    with zipfile.ZipFile(
        temporary, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9,
    ) as archive:
        payload = (item for item in root.rglob("*") if item.is_file())
        for path in sorted(payload, key=lambda item: item.relative_to(root).as_posix()):
            relative = path.relative_to(root).as_posix()
            info = zipfile.ZipInfo(relative, FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            info.create_system = 3
            archive.writestr(info, path.read_bytes(), compress_type=zipfile.ZIP_DEFLATED,
                             compresslevel=9)
    temporary.replace(output)


def package(
    target_name: str, profile_path: Path, skia_root: Path,
    toolchain_path: Path, output_dir: Path, variant: str = "release",
) -> Path:
    profile = load_profile(profile_path)
    target = target_definition(profile, target_name)
    toolchain = json.loads(toolchain_path.read_text(encoding="utf-8"))
    identity = make_identity(
        profile, target_name, toolchain, profile_path=profile_path,
        variant=variant,
    )
    build_dir = skia_root / "out" / output_name(profile, target_name, variant)
    revision_marker = skia_root / ".canvas-poc-revision"
    revision = (
        revision_marker.read_text(encoding="utf-8").strip()
        if revision_marker.exists() else ""
    )
    if revision and revision != profile["skia_commit"]:
        raise RuntimeError("Skia checkout revision does not match the SDK profile")

    with tempfile.TemporaryDirectory(prefix=f"canvas-skia-{target_name}-") as temporary:
        stage = Path(temporary) / "sdk"
        shutil.copytree(skia_root / "include", stage / "include")
        for header in MODULE_HEADERS:
            copy_file(skia_root / header, stage / header)
        for directory in profile.get("module_header_dirs", []):
            source = skia_root / directory
            if not source.is_dir():
                raise RuntimeError(f"required SDK header directory is missing: {source}")
            shutil.copytree(source, stage / directory)
        for header in profile.get("module_headers", []):
            copy_file(skia_root / header, stage / header)
        copy_file(skia_root / FONT, stage / FONT)
        licenses = dict(LICENSES)
        licenses.update(profile.get("licenses", {}))
        for destination, source in licenses.items():
            copy_file(skia_root / source, stage / "licenses" / destination)
        dependency_lock = json.loads(
            (Path(__file__).resolve().parents[2] / "deps.lock.json").read_text(
                encoding="utf-8"
            )
        )["dependencies"]
        for destination, dependency_name in profile.get(
            "fixture_fonts", {}
        ).items():
            dependency = dependency_lock[dependency_name]
            source = ROOT / ".deps/assets" / Path(dependency["source"]).name
            if not source.is_file() or file_sha256(source) != dependency["sha256"]:
                raise RuntimeError(
                    f"locked font fixture is missing or corrupt: {source}; run "
                    "python3 tools/bootstrap_deps.py --font-only"
                )
            copy_file(source, stage / destination)
        for destination, dependency_name in profile.get(
            "license_dependencies", {}
        ).items():
            dependency = dependency_lock[dependency_name]
            download_locked_file(
                dependency["url"], dependency["sha256"],
                stage / "licenses" / destination,
            )
        for runtime_file in profile.get("runtime_files", []):
            if runtime_file["target"] != target_name:
                continue
            copy_file(
                build_dir / runtime_file["source"],
                stage / runtime_file["destination"],
            )
        runtime_destinations = {
            item["destination"] for item in profile.get("runtime_files", [])
            if item["target"] == target_name
        }
        libraries = target["libraries"]
        library_sources: list[tuple[Path, str]] = []
        if libraries == "discover":
            library_sources = load_archive_closure(build_dir, target["platform"])
            libraries = [name for _, name in library_sources]
        else:
            library_sources = [(build_dir / name, name) for name in libraries]
        full = profile.get("schema_version") == 2
        config_text = cmake_config(
            libraries, target["platform"],
            cjk_font=(
                "resources/fonts/NotoSansCJK-VF-subset.otf.ttc"
                in profile.get("fixture_fonts", {})
            ),
            icu_data="runtime/windows/icudtl.dat" in runtime_destinations,
            full=full,
        ).replace("@CANVAS_SKIA_VARIANT@", variant)
        for source, library in library_sources:
            copy_library(
                source, stage / "lib" / library, target["platform"],
            )
        config = stage / "lib/cmake/CanvasSkia/CanvasSkiaConfig.cmake"
        config.parent.mkdir(parents=True, exist_ok=True)
        config.write_bytes(config_text.encode("utf-8"))
        (stage / "args.gn").write_bytes(
            normalized_args_text(profile, target_name, variant).encode("utf-8")
        )

        files = []
        payload = (item for item in stage.rglob("*") if item.is_file())
        for path in sorted(payload, key=lambda item: item.relative_to(stage).as_posix()):
            relative = path.relative_to(stage).as_posix()
            files.append({
                "path": relative,
                "sha256": file_sha256(path),
                "size": path.stat().st_size,
                "role": role(relative),
            })
        manifest = {
            "schema_version": 2 if full else 1,
            "format": FULL_SDK_FORMAT if full else SDK_FORMAT,
            "sdk_id": canonical_sha256(identity),
            "identity": identity,
            "files": files,
        }
        if full:
            manifest["capabilities"] = profile["capabilities"]
            manifest["unsupported_reasons"] = profile.get("unsupported_reasons", {})
            manifest["archive_closure"] = [
                {
                    "source_path": source.relative_to(build_dir).as_posix(),
                    "packaged_path": f"lib/{packaged}",
                    "sha256": file_sha256(stage / "lib" / packaged),
                    "size": (stage / "lib" / packaged).stat().st_size,
                }
                for source, packaged in library_sources
            ]
        (stage / "manifest.json").write_bytes(
            (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
        )
        suffix = f"-{variant}" if full else ""
        asset = output_dir / f"skia-sdk-{profile['profile']}-{target_name}{suffix}.zip"
        write_zip(stage, asset)
    if profile.get("schema_version") == 2 and variant in ("debug", "asan"):
        with tempfile.TemporaryDirectory(prefix=f"canvas-skia-symbols-{target_name}-") as temporary:
            symbols_root = Path(temporary)
            candidates = [
                path for path in build_dir.rglob("*")
                if path.is_file() and (
                    path.suffix.lower() in (".pdb", ".dwarf", ".map", ".debug")
                    or ".dSYM" in path.parts
                )
            ]
            entries = []
            for source in sorted(candidates):
                relative = source.relative_to(build_dir).as_posix().replace("/", "__")
                destination = symbols_root / "symbols" / relative
                copy_file(source, destination)
                entries.append({
                    "path": f"symbols/{relative}",
                    "sha256": file_sha256(destination),
                    "size": destination.stat().st_size,
                })
            metadata = {
                "schema_version": 1, "format": "canvas-skia-symbols-v1",
                "sdk_id": manifest["sdk_id"],
                "target": target_name, "variant": variant,
                "embedded_symbols": True, "files": entries,
            }
            (symbols_root / "symbols.json").write_text(
                json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8",
            )
            symbols_asset = output_dir / (
                f"skia-sdk-{profile['profile']}-{target_name}-{variant}-symbols.zip"
            )
            write_zip(symbols_root, symbols_asset)
    print(json.dumps({
        "asset": str(asset),
        "sha256": file_sha256(asset),
        "sdk_id": manifest["sdk_id"],
        "target": target_name,
    }, sort_keys=True))
    return asset


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--variant", choices=("release", "debug", "asan"), default="release")
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--skia-root", type=Path, default=SKIA_ROOT)
    parser.add_argument("--toolchain-json", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    package(
        args.target, args.profile.resolve(), args.skia_root.resolve(),
        args.toolchain_json.resolve(), args.output.resolve(), args.variant,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
