#pragma once

#include "canvas/semantic/operation.hpp"
#include "canvas/semantic/semantic_error.hpp"

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace canvas::semantic {

struct CanonicalField final {
    std::uint32_t id = 0;
    std::vector<std::uint8_t> bytes;
};

struct CodecResult final {
    SemanticError error = SemanticError::kNone;
    std::vector<std::uint8_t> bytes;
    [[nodiscard]] bool ok() const noexcept { return error == SemanticError::kNone; }
};

struct OperationFieldPresence final {
    bool schema_version = false;
    bool payload_version = false;
};

struct DecodedOperation final {
    Operation operation{};
    OperationFieldPresence presence{};
    std::vector<CanonicalField> fields;
    SemanticError error = SemanticError::kNone;
    DecodedOperation() = default;
    DecodedOperation(Operation operation_value, std::vector<CanonicalField> fields_value,
                     SemanticError error_value)
        : operation(std::move(operation_value)), fields(std::move(fields_value)), error(error_value) {}
    DecodedOperation(Operation operation_value, OperationFieldPresence presence_value,
                     std::vector<CanonicalField> fields_value, SemanticError error_value)
        : operation(std::move(operation_value)), presence(presence_value), fields(std::move(fields_value)), error(error_value) {}
    [[nodiscard]] bool ok() const noexcept { return error == SemanticError::kNone; }
};

struct StableSeedCase final {
    std::string stable_id;
};

enum class GoldenCodecStage : std::uint8_t {
    kNone = 0,
    kWirePreflight,
    kProtoDecode,
    kDtoMap,
    kNormalize,
    kValidate,
    kCanonicalEncode,
    kRuntimeUnavailable,
};

enum class GoldenCanonicality : std::uint8_t {
    kCanonical = 0,
    kNonCanonicalInput,
};

struct GoldenCodecObservation final {
    bool accepted = false;
    GoldenCanonicality canonicality = GoldenCanonicality::kCanonical;
    GoldenCodecStage stage = GoldenCodecStage::kNone;
    std::string category;
    std::vector<std::uint8_t> canonical_bytes;
    // Verification-only encoding-neutral projection. Generated protobuf DTOs
    // remain private to codec.cpp; this JSON is an observation surface for
    // independent leaf-golden differentials, not a public SDK model.
    std::string semantic_projection_json;

    GoldenCodecObservation() = default;
    GoldenCodecObservation(
        bool accepted_value,
        GoldenCanonicality canonicality_value,
        GoldenCodecStage stage_value,
        std::string category_value,
        std::vector<std::uint8_t> canonical_bytes_value,
        std::string semantic_projection_json_value = {})
        : accepted(accepted_value),
          canonicality(canonicality_value),
          stage(stage_value),
          category(std::move(category_value)),
          canonical_bytes(std::move(canonical_bytes_value)),
          semantic_projection_json(std::move(semantic_projection_json_value)) {}
};

class SemanticCodec final {
  public:
    static CodecResult encodeOperation(OperationKind kind, const std::vector<CanonicalField>& fields);
    // Experimental G1-02 probe. Protobuf types remain private to codec.cpp;
    // this returns the canonical runtime bytes without exposing that ABI.
    static CodecResult encodeProtobufOperation(OperationKind kind);
    static DecodedOperation decodeOperation(const std::vector<std::uint8_t>& bytes);
    static CodecResult encodeCanonicalF64(double value);
    static std::vector<StableSeedCase> stableSeedV01();
    // Experimental verification seam. Expected golden bytes are never
    // generated by this API; it only observes production codec behavior.
    static GoldenCodecObservation observeGoldenFixture(
        const std::string& root_type,
        const std::vector<std::uint8_t>& bytes,
        bool strict_canonical);
};

} // namespace canvas::semantic
