#pragma once

#include "canvas/semantic/operation.hpp"
#include "canvas/semantic/semantic_error.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace canvas::semantic {

struct CanonicalField final {
    std::uint32_t id = 0;
    std::vector<std::uint8_t> bytes;
};

struct CodecResult final {
    SemanticError error = SemanticError::kNone;
    std::vector<std::uint8_t> bytes;
    [[nodiscard]] bool ok() const noexcept { return error == SemanticError::kNone; }
};

struct DecodedOperation final {
    Operation operation{};
    std::vector<CanonicalField> fields;
    SemanticError error = SemanticError::kNone;
    [[nodiscard]] bool ok() const noexcept { return error == SemanticError::kNone; }
};

struct StableSeedCase final {
    std::string stable_id;
};

enum class GoldenCodecStage : std::uint8_t {
    kNone = 0,
    kWirePreflight,
    kProtoDecode,
    kDtoMap,
    kNormalize,
    kValidate,
    kCanonicalEncode,
    kRuntimeUnavailable,
};

enum class GoldenCanonicality : std::uint8_t {
    kCanonical = 0,
    kNonCanonicalInput,
};

struct GoldenCodecObservation final {
    bool accepted = false;
    GoldenCanonicality canonicality = GoldenCanonicality::kCanonical;
    GoldenCodecStage stage = GoldenCodecStage::kNone;
    std::string category;
    std::vector<std::uint8_t> canonical_bytes;
};

class SemanticCodec final {
  public:
    static CodecResult encodeOperation(OperationKind kind, const std::vector<CanonicalField>& fields);
    // Experimental G1-02 probe. Protobuf types remain private to codec.cpp;
    // this returns the canonical runtime bytes without exposing that ABI.
    static CodecResult encodeProtobufOperation(OperationKind kind);
    static DecodedOperation decodeOperation(const std::vector<std::uint8_t>& bytes);
    static CodecResult encodeCanonicalF64(double value);
    static std::vector<StableSeedCase> stableSeedV01();
    // Experimental verification seam. Expected golden bytes are never
    // generated by this API; it only observes production codec behavior.
    static GoldenCodecObservation observeGoldenFixture(
        const std::string& root_type,
        const std::vector<std::uint8_t>& bytes,
        bool strict_canonical);
};

} // namespace canvas::semantic
