// Generated by tools/generate_geometry_accounting_projection.py from geometry_accounting_v1.yaml.
// Do not edit this file manually; regenerate and run the binding checker.
#pragma once

#include <cstddef>

namespace canvas::semantic::geometry_accounting_v1 {

inline constexpr std::size_t kLimit = 2000000U;
inline constexpr std::size_t kMoveToPoint = 1U;
inline constexpr std::size_t kLineToEnd = 1U;
inline constexpr std::size_t kQuadTo = 2U;
inline constexpr std::size_t kCubicTo = 3U;
inline constexpr std::size_t kStrokeSample = 1U;
inline constexpr std::size_t kDabInstance = 3U;
inline constexpr std::size_t kEraseCubicSegment = 6U;

} // namespace canvas::semantic::geometry_accounting_v1
