// The Windows host feeds WM_POINTER/GetPointer*History batches into the
// protocol and owns the HWND/DComp visual. Arc only owns the Preview visual;
// no HWND or Canonical swapchain is stored in this target.
#define ARC_PLATFORM_KIND ARC_PLATFORM_WINDOWS
#define ARC_CREATE_BACKEND CreateWindowsBackend
#define ARC_CREATE_INPUT_SOURCE CreateWindowsInputSource
#define ARC_REQUIRES_PLATFORM_HANDLE 1
#define ARC_INPUT_CAPABILITIES \
  (ARC_INPUT_CAPABILITY_PRESSURE | ARC_INPUT_CAPABILITY_TILT | \
   ARC_INPUT_CAPABILITY_CONTACT | ARC_INPUT_CAPABILITY_HISTORY | \
   ARC_INPUT_CAPABILITY_HOVER | ARC_INPUT_CAPABILITY_ERASER)
#define ARC_PRESENTATION_CAPABILITIES \
  (ARC_PRESENTATION_CAPABILITY_INDEPENDENT_TARGET | \
   ARC_PRESENTATION_CAPABILITY_REPLACE_TRUNCATE | \
   ARC_PRESENTATION_CAPABILITY_PRESENT_RECEIPT | \
   ARC_PRESENTATION_CAPABILITY_SHARED_GPU_DEVICE)
#include "../backend_factory.inc"
