// Web presentation is an overlay WebGL canvas. Browser PointerEvents remain
// the host boundary; this target never routes hot-path input through React.
#define ARC_PLATFORM_KIND ARC_PLATFORM_WEB
#define ARC_CREATE_BACKEND CreateWebBackend
#define ARC_CREATE_INPUT_SOURCE CreateWebInputSource
#define ARC_REQUIRES_PLATFORM_HANDLE 1
#define ARC_INPUT_CAPABILITIES \
  (ARC_INPUT_CAPABILITY_PRESSURE | ARC_INPUT_CAPABILITY_TILT | \
   ARC_INPUT_CAPABILITY_COALESCED | ARC_INPUT_CAPABILITY_HISTORY)
#define ARC_PRESENTATION_CAPABILITIES \
  (ARC_PRESENTATION_CAPABILITY_INDEPENDENT_TARGET | \
   ARC_PRESENTATION_CAPABILITY_REPLACE_TRUNCATE | \
   ARC_PRESENTATION_CAPABILITY_PRESENT_RECEIPT | \
   ARC_PRESENTATION_CAPABILITY_DESYNCHRONIZED)
#include "../backend_factory.inc"
