"""Real CMake orchestration tests; stub sources are not Axiom runtime proof.

The production CMakeLists is copied unchanged. A tiny host generator records
calls; a target CONFIG package exports only the library (or a poison protoc).
Full Axiom compilation against real SDKs is exercised by the hosted lane.
"""
from pathlib import Path
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
import unittest

ROOT = Path(__file__).resolve().parents[2]
CMAKE = ROOT / 'runtime/semantic/CMakeLists.txt'


class SemanticCmakeStaticTest(unittest.TestCase):
    def test_codegen_uses_explicit_host_file_not_target_executable(self):
        source = CMAKE.read_text(encoding='utf-8')
        self.assertIn('set(AXIOM_PROTOC "" CACHE FILEPATH', source)
        self.assertIn('COMMAND "${AXIOM_PROTOC}"', source)
        self.assertIn('DEPENDS "${AXIOM_PROTOC}" ${AXIOM_PROTO_FILES}', source)
        self.assertNotIn('protobuf::protoc', source)
        self.assertIn('PRIVATE protobuf::libprotobuf', source)

    def test_current_hosted_callers_pass_both_roots_explicitly(self):
        for name in ('g1-semantic-codec.yml', 'build-environment-contract.yml'):
            source = (ROOT / '.github/workflows' / name).read_text(encoding='utf-8')
            with self.subTest(workflow=name):
                self.assertIn('-DCMAKE_PREFIX_PATH="$AXIOM_SEMANTIC_RUNTIME_ROOT"', source)
                self.assertIn('-DAXIOM_PROTOC="$AXIOM_PROTOC"', source)

    def test_cmake_qualification_runs_before_producer_and_on_real_v2_package(self):
        source = (ROOT / '.github/workflows/semantic-sdk-producer-contract.yml').read_text()
        discovery = source.split('  runtime-discovery:', 1)[1].split('  runtimes:', 1)[0]
        self.assertIn('verification.tests.test_semantic_cmake_contract', discovery)
        self.assertIn('  axiom-cmake-consumer:', source)
        job = source.split('  axiom-cmake-consumer:', 1)[1]
        self.assertIn('needs: release-set', job)
        self.assertIn('semantic-v2-release-set-candidate', job)
        self.assertIn('setup_environment', job)
        self.assertIn('consumer_cmake_arguments', job)
        self.assertIn('--output-junit', job)
        self.assertIn('-DCANVAS_SEMANTIC_ENABLE_PROTOBUF=OFF', job)
        self.assertNotIn('bootstrap_deps.py --semantic-codec', job)
        self.assertNotIn('build_runtime.py', job)
        self.assertNotIn('contents: write', job)


@unittest.skipUnless(shutil.which('cmake') and shutil.which('ninja'), 'CMake and Ninja required')
class SemanticCmakeExecutionTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix='axiom cmake contract ')
        self.addCleanup(self.tmp.cleanup)
        self.base = Path(self.tmp.name).resolve()
        self.project = self.base / 'project with spaces'
        self.build = self.base / 'build with spaces'
        semantic = self.project / 'semantic'
        (semantic / 'tools').mkdir(parents=True)
        source = CMAKE.read_text(encoding='utf-8')
        (semantic / 'CMakeLists.txt').write_text(source, encoding='utf-8')
        (semantic / 'tools/CMakeLists.txt').write_text('# No product tooling in the orchestration fixture.\n')
        for name in re.findall(r'src/[a-z_]+\.cpp', source):
            path = semantic / name
            path.parent.mkdir(exist_ok=True)
            path.write_text('// Fixture: CMake configuration only.\n')
        self.proto = self.project / 'schema/axiom/v1/proto/contract.proto'
        self.proto.parent.mkdir(parents=True)
        self.proto.write_text('syntax = "proto3"; message Contract { int32 id = 1; }\n')
        (self.project / 'CMakeLists.txt').write_text('''cmake_minimum_required(VERSION 3.30)
project(SemanticHostContract LANGUAGES CXX)
add_library(canvas_runtime_foundation INTERFACE)
add_subdirectory(semantic)
file(WRITE "${CMAKE_BINARY_DIR}/cross.txt" "${CMAKE_CROSSCOMPILING}")
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/links.txt"
     CONTENT "$<TARGET_PROPERTY:canvas_runtime_semantic,LINK_LIBRARIES>")
''')
        self.runtime = self.base / 'target runtime'
        self.config = self.runtime / 'lib/cmake/protobuf/protobuf-config.cmake'
        self.config.parent.mkdir(parents=True)
        self.config.write_text('add_library(protobuf::libprotobuf INTERFACE IMPORTED)\n')
        host = self.base / 'host tools'
        host.mkdir()
        generator = host / 'generate.py'
        generator.write_text('''import pathlib, sys
out = pathlib.Path(next(a.split("=", 1)[1] for a in sys.argv if a.startswith("--cpp_out=")))
out.mkdir(parents=True, exist_ok=True)
for ext in ("cc", "h"):
    (out / ("contract.pb." + ext)).write_text("// generated by explicit host tool\\n")
with (out / "calls.txt").open("a") as calls:
    calls.write("host\\n")
''')
        self.protoc = host / ('protoc.cmd' if os.name == 'nt' else 'protoc')
        if os.name == 'nt':
            self.protoc.write_text(f'@echo off\n"{sys.executable}" "{generator}" %*\n', encoding='utf-8')
        else:
            self.protoc.write_text(f'#!/bin/sh\nexec {shlex.quote(sys.executable)} {shlex.quote(str(generator))} "$@"\n')
            self.protoc.chmod(0o755)

    def configure(self, *, host=True, enabled=True, extra=()):
        command = ['cmake', '-S', str(self.project), '-B', str(self.build), '-G', 'Ninja',
                   '-DCANVAS_BUILD_SEMANTIC=ON', '-DBUILD_TESTING=OFF',
                   '-DCANVAS_SEMANTIC_ENABLE_PROTOBUF=' + ('ON' if enabled else 'OFF'),
                   '-DCMAKE_PREFIX_PATH=' + self.runtime.as_posix(),
                   '-DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF',
                   '-DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF']
        if host:
            command.append('-DAXIOM_PROTOC=' + self.protoc.as_posix())
        return subprocess.run(command + list(extra), capture_output=True, text=True)

    def generate(self):
        result = subprocess.run(['cmake', '--build', str(self.build), '--target',
                                 'semantic/generated/contract.pb.h'], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        return (self.build / 'semantic/generated/calls.txt').read_text().splitlines()

    def expect_success(self, **options):
        result = self.configure(**options)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_runtime_without_protoc_target_generates_using_separate_host(self):
        self.expect_success()
        self.assertEqual(self.generate(), ['host'])
        self.assertIn('protobuf::libprotobuf', (self.build / 'links.txt').read_text())
        self.assertNotIn('protobuf::protoc', (self.build / 'links.txt').read_text())
        self.assertIn('AXIOM_PROTOC:FILEPATH=', (self.build / 'CMakeCache.txt').read_text())

    def test_cross_config_does_not_execute_target_protoc_or_emulator(self):
        with self.config.open('a') as output:
            output.write('add_executable(protobuf::protoc IMPORTED)\n'
                         'set_target_properties(protobuf::protoc PROPERTIES '
                         'IMPORTED_LOCATION "/never-run-target-protoc")\n')
        # Generic disables CMake's Windows/MSVC platform flags. Select Windows
        # explicitly on Windows instead: CMake still sets CROSSCOMPILING=TRUE,
        # but its compiler sanity check uses the correct native ABI flags.
        system = 'Windows' if os.name == 'nt' else 'Generic'
        self.expect_success(extra=(f'-DCMAKE_SYSTEM_NAME={system}',
                                   '-DCMAKE_CROSSCOMPILING_EMULATOR=/never-run-emulator'))
        self.assertEqual((self.build / 'cross.txt').read_text(), 'TRUE')
        self.assertEqual(self.generate(), ['host'])

    def test_host_is_mandatory_even_when_runtime_exports_protoc(self):
        with self.config.open('a') as output:
            output.write('add_executable(protobuf::protoc IMPORTED)\n'
                         f'set_target_properties(protobuf::protoc PROPERTIES IMPORTED_LOCATION "{self.protoc.as_posix()}")\n')
        result = self.configure(host=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('AXIOM_PROTOC', result.stdout + result.stderr)

    def test_missing_host_path_fails_configuration(self):
        self.protoc.unlink()
        result = self.configure()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('AXIOM_PROTOC', result.stdout + result.stderr)

    def test_directory_cannot_be_used_as_host_executable(self):
        self.protoc.unlink()
        self.protoc.mkdir()
        result = self.configure()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('AXIOM_PROTOC', result.stdout + result.stderr)

    def test_missing_target_library_fails_configuration(self):
        self.config.write_text('# No target library exported.\n')
        result = self.configure()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('protobuf::libprotobuf', result.stdout + result.stderr)

    def test_protobuf_off_needs_neither_package_nor_host(self):
        shutil.rmtree(self.runtime)
        self.protoc.unlink()
        self.expect_success(host=False, enabled=False)
        self.assertNotIn('protobuf', (self.build / 'links.txt').read_text())

    def test_host_and_proto_changes_regenerate_but_unchanged_build_does_not(self):
        self.expect_success()
        self.assertEqual(self.generate(), ['host'])
        self.assertEqual(self.generate(), ['host'])
        time.sleep(1.1)
        os.utime(self.protoc, None)
        self.assertEqual(self.generate(), ['host', 'host'])
        time.sleep(1.1)
        with self.proto.open('a') as output:
            output.write('// Updated schema input.\n')
        self.assertEqual(self.generate(), ['host', 'host', 'host'])
        self.assertEqual(self.generate(), ['host', 'host', 'host'])


if __name__ == '__main__':
    unittest.main()
