#!/usr/bin/env python3
"""Generate the small C++ projection of the frozen geometry accounting YAML."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
PROJECTION = ROOT / "schema/axiom/v1/canonical/geometry_accounting_v1.yaml"
DEFAULT_OUTPUT = ROOT / "runtime/semantic/include/canvas/semantic/geometry_accounting_v1.hpp"


def load_yaml(path: Path) -> dict:
    script = r'''
      require 'yaml'
      require 'json'
      source = File.read(ARGV.fetch(0))
      puts JSON.generate(YAML.safe_load(source, aliases: false))
    '''
    result = subprocess.run(["ruby", "-e", script, str(path)], capture_output=True, text=True)
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "invalid geometry projection YAML")
    value = json.loads(result.stdout)
    if not isinstance(value, dict):
        raise RuntimeError("geometry projection must be a mapping")
    return value


def render(projection: dict) -> str:
    carriers = projection["carriers"]
    values = {
        "kLimit": projection["limit"]["value"],
        "kMoveToPoint": carriers["MoveTo.point"],
        "kLineToEnd": carriers["LineTo.end"],
        "kQuadTo": carriers["QuadTo.control"] + carriers["QuadTo.end"],
        "kCubicTo": carriers["CubicTo.control1"] + carriers["CubicTo.control2"] + carriers["CubicTo.end"],
        "kStrokeSample": carriers["StrokeSample.position"],
        "kDabInstance": carriers["DabInstance.center"] + carriers["DabInstance.size"] + carriers["DabInstance.rotation"] + carriers["DabInstance.opacity"],
        "kEraseCubicSegment": 2 * carriers["EraseKnot.position"] + 2 * carriers["EraseKnot.radius"] + carriers["EraseCubicSegment.control1"] + carriers["EraseCubicSegment.control2"],
    }
    lines = [
        "// Generated by tools/generate_geometry_accounting_projection.py from geometry_accounting_v1.yaml.",
        "// Do not edit this file manually; regenerate and run the binding checker.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace canvas::semantic::geometry_accounting_v1 {",
        "",
    ]
    for name, value in values.items():
        lines.append(f"inline constexpr std::size_t {name} = {value}U;")
    lines.extend(["", "} // namespace canvas::semantic::geometry_accounting_v1", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(load_yaml(PROJECTION))
    output = args.output if args.output.is_absolute() else ROOT / args.output
    if args.check:
        return 0 if output.read_text(encoding="utf-8") == expected else 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
