// Android Native CanvasView/JNI supplies MotionEvent history directly to the
// protocol. The low-latency/front-buffer target is owned here, never by RN JS.
#define ARC_PLATFORM_KIND ARC_PLATFORM_ANDROID
#define ARC_CREATE_BACKEND CreateAndroidBackend
#define ARC_CREATE_INPUT_SOURCE CreateAndroidInputSource
#define ARC_REQUIRES_PLATFORM_HANDLE 1
#define ARC_INPUT_CAPABILITIES \
  (ARC_INPUT_CAPABILITY_PRESSURE | ARC_INPUT_CAPABILITY_TILT | \
   ARC_INPUT_CAPABILITY_CONTACT | ARC_INPUT_CAPABILITY_HISTORY | \
   ARC_INPUT_CAPABILITY_HOVER | ARC_INPUT_CAPABILITY_ERASER)
#define ARC_PRESENTATION_CAPABILITIES \
  (ARC_PRESENTATION_CAPABILITY_INDEPENDENT_TARGET | \
   ARC_PRESENTATION_CAPABILITY_REPLACE_TRUNCATE | \
   ARC_PRESENTATION_CAPABILITY_PRESENT_RECEIPT | \
   ARC_PRESENTATION_CAPABILITY_FRONT_BUFFER | \
   ARC_PRESENTATION_CAPABILITY_SHARED_GPU_DEVICE)
#include "../backend_factory.inc"
